### ISSUE TITLE
`vagrant halt && vagrant up` supported?

### ISSUE THREAD

**Issue by MaxDaten** [pires/kubernetes-vagrant-coreos-cluster#100]
me again. Is `vagrant halt` supported? Currently it seems booting the cluster up again hangs in waiting for the master to become ready, or at least booting up is extremely slow. Or is this a kubernetes problem?

With a fresh start:
```
$ vagrant up
# waiting for the cluster to become ready
$ vagrant halt
$ vagrant up
# hangs in
==> master: Waiting for Kubernetes master to become ready...
```

during this, I can ssh into the master with `vagrant ssh master` in a different shell. The master is up but the api is not accessable:

```
$ kubectl cluster-info
Kubernetes master is running at http://172.17.8.101:8080
$ kubectl get events
Error: Get http://http://172.17.8.101:8080/api/v1beta3/namespaces/default/events: dial tcp 172.17.8.101:8080 connection rufused
```

Is this a known limitation of kubernetes and vagrant? But I assume it should be possible according to
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md#interacting-with-your-kubernetes-cluster-with-vagrant

```
$ vagrant version
Installed Version: 1.7.2
$ VBoxManage --version
4.3.28r100309
```

**Comment by pires** [comment]
There's a lot of stuff that needs to be downloaded and bootstrapped. I've seen clusters taking up to 5 minutes while others take 45 seconds. Internet speed, for instance, is a major factor.

**Comment by MaxDaten** [comment]
Yes I observed this. I hoped that `vagrant halt && vagrant up` is a bit faster after the initial `vagrant up`, especially with docker cache in the cluster. But `vagrant up` after a `vagrant halt` seems to be a way slower than a fresh initial `vagrant up`.

- timed the first initial vagrant up: 
  - `vagrant up  7.85s user 4.40s system 4% cpu 4:51.01 total`
- timed vagrant up after vagrant halt:
  - `vagrant up  7.14s user 4.31s system 0% cpu 26:17.61 total`

both on the same machine with the same internet connection. And even after the halted cluster is finally up during up two warnings are emitted and the API is still not reachable: 

```
==> master: Waiting for Kubernetes master to become ready...
Error: Post http://172.17.8.101:8080/api/v1beta3/namespaces/default/replicationcontrollers: dial tcp 172.17.8.101:8080: connection refused
Error: Post http://172.17.8.101:8080/api/v1beta3/namespaces/default/services: dial tcp 172.17.8.101:8080: connection refused
# ...
$ kubectl cluster-info
Kubernetes master is running at http://172.17.8.101:8080
$ kubectl get events
Error: Get http://172.17.8.101:8080/api/v1beta3/namespaces/default/events: dial tcp 172.17.8.101:8080: connection refused
```

I'm not sure, but I would expect `vagrant up` to be faster on a halted cluster, but it isn't.

**Comment by pires** [comment]
I don't even expect Kubernetes stuff to actually survive a halt. It's not meant to do it, yet. There are dozens of issues related to high-availability and reboot-survival.

Anyway, if you can dive deep and figure out what's going on, I'm more than open to analyze all your feedback and eventually provide a workaround.

**Comment by MaxDaten** [comment]
okay, I can live wit it. I was just curious if this a 'normal' expected behaviour. When I've gained more insight into Kubernetes I can try to investigate it further.

**Comment by heytrav** [comment]
At any rate it would be nice if it were supported. I run this on my laptop and can't always afford to have it going constantly. I frequently need to shut things down on long trips due to battery, etc. Lately I often need to rebuild my entire environment from scratch which can be quite time consuming.

**Comment by pires** [comment]
Kubernetes is made for the cloud not one's laptop. This is for development purposes and ofc we will find a lot of stuff that's just hard to support. 

One other solution is to build your own binaries and provide them + having a local registry with all images used for DNS containers.

**Comment by heytrav** [comment]
Probably a bit misleading then that the opening line of the [Kubernetes vagrant wiki](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md) says:

> Running kubernetes with Vagrant (and VirtualBox) is an easy way to run/test/develop on your local machine (Linux, Mac OS X).

**Comment by pires** [comment]
This project is not related to official Vagrant support. And I doubt it works as you expect. Let me know of your findings.

**Comment by MaxDaten** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/8660
it seems this was the issue and it's now fixed for me. I can now `halt` and `up` as often as I want. And `vagrant up` of a halted cluster is a way faster (1:51 min) than a complete fresh setup (5:30 min).

**Comment by pires** [comment]
We don't use salt, but if it works, awesome!
