### ISSUE TITLE
Timeouts when trying to post to connect

### ISSUE THREAD

**Issue by tslater** [pires/kubernetes-vagrant-coreos-cluster#101]
When I install (or try and use kubectl subsequently) I get errors when trying to connect to the api:
```
Error: Post https://10.245.1.2/api/v1beta3/namespaces/default/replicationcontrollers: dial tcp 10.245.1.2:443: i/o timeout
Error: Post https://10.245.1.2/api/v1beta3/namespaces/default/services: dial tcp 10.245.1.2:443: i/o timeout
```
I made sure to run ```VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0```
...and have tried rebuilding the whole thing multiple times.
My .bash_profile has the following added to it:
````
export FLEETCTL_ENDPOINT=http://172.17.8.101:4001
export KUBERNETES_MASTER=http://172.17.8.101:8080
````

Should those be matching? Is there a hidden config for kubectl?

**Comment by tslater** [comment]
Hold on, I think i might have found ~/.kube/config

**Comment by wstrange** [comment]
I recently updated my google gcloud tools - and it caused kubectl to stop working. kubectl now looks in ~/.kube/config 

A quick and dirty fix is to move this file (config.bak)

You can also edit this file and add:
- cluster:
    server: http://172.17.8.101:8080
  name: vagrant-k8

Then set your context with kubectl to be vagrant-k8

**Comment by pires** [comment]
10.245.x.x is not even addressing used in this project. 

Thank you @wstrange
