### ISSUE TITLE
kube-dns pod does not appear after first vagrant up

### ISSUE THREAD

**Issue by karmux** [pires/kubernetes-vagrant-coreos-cluster#103]
When I first create machines with

```
USE_DOCKERCFG=true DOCKERCFG=../containers/cloud_config/.dockercfg NUM_INSTANCES=1 MASTER_MEM=1024 MASTER_CPUS=2 NODE_MEM=4096 NODE_CPUS=2 vagrant up
```

then no kube-dns pod is created

```
$ kubectl get pods                     
POD       IP        CONTAINER(S)   IMAGE(S)   HOST      LABELS    STATUS    CREATED   MESSAGE
```

But when I do halt and up again, then kube-dns pod appears into `kubectl get pods` output:

```
USE_DOCKERCFG=true DOCKERCFG=../containers/cloud_config/.dockercfg NUM_INSTANCES=1 MASTER_MEM=1024 MASTER_CPUS=2 NODE_MEM=4096 NODE_CPUS=2 vagrant halt
```

```
USE_DOCKERCFG=true DOCKERCFG=../containers/cloud_config/.dockercfg NUM_INSTANCES=1 MASTER_MEM=1024 MASTER_CPUS=2 NODE_MEM=4096 NODE_CPUS=2 vagrant up
```

```
$ kubectl get pods
POD              IP            CONTAINER(S)   IMAGE(S)                                         HOST            LABELS                                                STATUS    CREATED          MESSAGE
kube-dns-8qh8o   10.244.37.2                                                                   172.17.8.102/   k8s-app=kube-dns,kubernetes.io/cluster-service=true   Running   5 minutes        
                               skydns         gcr.io/google_containers/skydns:2015-03-11-001                                                                         Running   About a minute   
                               kube2sky       gcr.io/google_containers/kube2sky:1.5                                                                                  Running   About a minute   
                               etcd           gcr.io/google_containers/etcd:2.0.9                                                                                    Running   About a minute
```

There is no errors in vagrant output and it always displays that it's configuring Kubernetes cluster DNS while bringing machines up.

**Comment by pires** [comment]
See #100

**Comment by pires** [comment]
Couldn't reproduce.

```
kubernetes-vagrant-coreos-cluster pires$ NUM_INSTANCES=1 MASTER_MEM=1024 MASTER_CPUS=2 NODE_MEM=4096 NODE_CPUS=2 vagrant up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'node-01' up with 'virtualbox' provider...
==> master: Running triggers before up...
==> master: Setting Kubernetes version 0.17.0
==> master: Configuring Kubernetes cluster DNS...
==> master: Importing base box 'coreos-alpha'...
==> master: Matching MAC address for NAT networking...
==> master: Checking if box 'coreos-alpha' is up to date...
==> master: Setting the name of the VM: kubernetes-vagrant-coreos-cluster_master_1432716795612_94814
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 => 2222 (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2222
    master: SSH username: core
    master: SSH auth method: private key
    master: Warning: Connection timeout. Retrying...
==> master: Machine booted and ready!
==> master: Setting hostname...
==> master: Configuring and enabling network interfaces...
==> master: Running provisioner: file...
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running triggers after up...
==> master: Sanitizing stuff...
Identity added: /Users/pires/.vagrant.d/insecure_private_key (/Users/pires/.vagrant.d/insecure_private_key)
==> master: Installing kubectl for the kubernetes version we just bootstrapped...
Downloading and installing darwin version of 'kubectl' v0.17.0 into /usr/local/bin. This may take a couple minutes, depending on your internet speed..
Password:
Setting environment variables..
==> master: Waiting for Kubernetes master to become ready...
replicationcontrollers/kube-dns
services/kube-dns
==> node-01: Importing base box 'coreos-alpha'...
==> node-01: Matching MAC address for NAT networking...
==> node-01: Checking if box 'coreos-alpha' is up to date...
==> node-01: Setting the name of the VM: kubernetes-vagrant-coreos-cluster_node-01_1432716970949_86055
==> node-01: Fixed port collision for 22 => 2222. Now on port 2200.
==> node-01: Clearing any previously set network interfaces...
==> node-01: Preparing network interfaces based on configuration...
    node-01: Adapter 1: nat
    node-01: Adapter 2: hostonly
==> node-01: Forwarding ports...
    node-01: 22 => 2200 (adapter 1)
==> node-01: Running 'pre-boot' VM customizations...
==> node-01: Booting VM...
==> node-01: Waiting for machine to boot. This may take a few minutes...
    node-01: SSH address: 127.0.0.1:2200
    node-01: SSH username: core
    node-01: SSH auth method: private key
    node-01: Warning: Connection timeout. Retrying...
==> node-01: Machine booted and ready!
==> node-01: Setting hostname...
==> node-01: Configuring and enabling network interfaces...
==> node-01: Running provisioner: file...
==> node-01: Running provisioner: shell...
    node-01: Running: inline script
==> node-01: Running triggers after up...
==> node-01: Waiting for Kubernetes minion [node-01] to become ready...
littlepires:kubernetes-vagrant-coreos-cluster pires$ kubectl get pods
POD              IP        CONTAINER(S)   IMAGE(S)                                         HOST            LABELS                                                STATUS    CREATED
kube-dns-3o969             etcd           gcr.io/google_containers/etcd:2.0.9              172.17.8.102/   k8s-app=kube-dns,kubernetes.io/cluster-service=true   Pending   3 minutes
                           kube2sky       gcr.io/google_containers/kube2sky:1.5
                           skydns         gcr.io/google_containers/skydns:2015-03-11-001
littlepires:kubernetes-vagrant-coreos-cluster pires$ kubectl get pods
POD              IP           CONTAINER(S)   IMAGE(S)                                         HOST            LABELS                                                STATUS    CREATED
kube-dns-3o969   10.244.5.2   etcd           gcr.io/google_containers/etcd:2.0.9              172.17.8.102/   k8s-app=kube-dns,kubernetes.io/cluster-service=true   Running   3 minutes
                              kube2sky       gcr.io/google_containers/kube2sky:1.5
                              skydns         gcr.io/google_containers/skydns:2015-03-11-001
```

**Comment by karmux** [comment]
I can confirm that there is actually no such issue.

Problem was that my VirtualBox went crazy since I hadn't restart my PC for long. VirtualBox ate all the CPU and was extremely slow. Probably some timeout occured or something that didn't let it install kube-dns. After I rebooted creating cluster went super fast and I have kube-dns too :)

**Comment by pires** [comment]
@karmux glad to know! Thank you for your feedback, nonetheless.

**Comment by tcichowicz** [comment]
I'm afraid that this issue still exists. Steps to reproduce:
1. `vagrant destroy`
2. `vagrant up` - no kube-dns
3. `vagrant up` - kube-dns pods and services are up and running

    $ vagrant destroy -f
    ==> node-02: Running triggers before destroy...
    ==> node-02: Destroying VM and associated drives...
    ==> node-02: Running cleanup tasks for 'file' provisioner...
    ==> node-02: Running cleanup tasks for 'file' provisioner...
    ==> node-02: Running cleanup tasks for 'shell' provisioner...
    ==> node-01: Running triggers before destroy...
    ==> node-01: Destroying VM and associated drives...
    ==> node-01: Running cleanup tasks for 'file' provisioner...
    ==> node-01: Running cleanup tasks for 'file' provisioner...
    ==> node-01: Running cleanup tasks for 'shell' provisioner...
    ==> master: Running triggers before destroy...
    ==> master: Destroying VM and associated drives...
    ==> master: Running cleanup tasks for 'file' provisioner...
    ==> master: Running cleanup tasks for 'file' provisioner...
    ==> master: Running cleanup tasks for 'shell' provisioner...
    $ DNS_UPSTREAM_SERVERS="172.17.42.1:53" USE_DOCKERCFG=true vagrant up --provider=virtualbox
    Bringing machine 'master' up with 'virtualbox' provider...
    Bringing machine 'node-01' up with 'virtualbox' provider...
    Bringing machine 'node-02' up with 'virtualbox' provider...
    ==> master: Running triggers before up...
    ==> master: Setting Kubernetes version 0.18.1
    ==> master: Configuring Kubernetes cluster DNS...
    ==> master: Importing base box 'coreos-alpha'...
    ==> master: Matching MAC address for NAT networking...
    ==> master: Checking if box 'coreos-alpha' is up to date...
    ==> master: Setting the name of the VM: vagrant-k8s_master_1434008859099_54866
    ==> master: Clearing any previously set network interfaces...
    ==> master: Preparing network interfaces based on configuration...
        master: Adapter 1: nat
        master: Adapter 2: hostonly
    ==> master: Forwarding ports...
        master: 22 => 2222 (adapter 1)
    ==> master: Running 'pre-boot' VM customizations...
    ==> master: Booting VM...
    ==> master: Waiting for machine to boot. This may take a few minutes...
        master: SSH address: 127.0.0.1:2222
        master: SSH username: core
        master: SSH auth method: private key
        master: Warning: Connection timeout. Retrying...
    ==> master: Machine booted and ready!
    ==> master: Setting hostname...
    ==> master: Configuring and enabling network interfaces...
    ==> master: Running provisioner: file...
    ==> master: Running provisioner: shell...
        master: Running: inline script
    ==> master: Running provisioner: file...
    ==> master: Running provisioner: file...
    ==> master: Running provisioner: shell...
        master: Running: inline script
    ==> master: Running triggers after up...
    ==> master: Sanitizing stuff...
    Identity added: /home/tomasz.cichowicz/.vagrant.d/insecure_private_key (rsa w/o comment)
    ==> master: Installing kubectl for the kubernetes version we just bootstrapped...
    Downloading and installing linux version of 'kubectl' v0.18.1 into /usr/local/bin. This may take a couple minutes, depending on your internet speed..
    Setting environment variables..
    ==> master: Waiting for Kubernetes master to become ready...
    The connection to the server localhost:8080 was refused - did you specify the right host or port?
    The connection to the server localhost:8080 was refused - did you specify the right host or port?
    ==> node-01: Importing base box 'coreos-alpha'...
    ==> node-01: Matching MAC address for NAT networking...
    ==> node-01: Checking if box 'coreos-alpha' is up to date...
    ==> node-01: Setting the name of the VM: vagrant-k8s_node-01_1434009162252_13564
    ==> node-01: Fixed port collision for 22 => 2222. Now on port 2200.
    ==> node-01: Clearing any previously set network interfaces...
    ==> node-01: Preparing network interfaces based on configuration...
        node-01: Adapter 1: nat
        node-01: Adapter 2: hostonly
    ==> node-01: Forwarding ports...
        node-01: 22 => 2200 (adapter 1)
    ==> node-01: Running 'pre-boot' VM customizations...
    ==> node-01: Booting VM...
    ==> node-01: Waiting for machine to boot. This may take a few minutes...
        node-01: SSH address: 127.0.0.1:2200
        node-01: SSH username: core
        node-01: SSH auth method: private key
        node-01: Warning: Connection timeout. Retrying...
    ==> node-01: Machine booted and ready!
    ==> node-01: Setting hostname...
    ==> node-01: Configuring and enabling network interfaces...
    ==> node-01: Running provisioner: file...
    ==> node-01: Running provisioner: shell...
        node-01: Running: inline script
    ==> node-01: Running provisioner: file...
    ==> node-01: Running provisioner: file...
    ==> node-01: Running provisioner: shell...
        node-01: Running: inline script
    ==> node-01: Running triggers after up...
    ==> node-01: Waiting for Kubernetes minion [node-01] to become ready...
    ==> node-02: Importing base box 'coreos-alpha'...
    ==> node-02: Matching MAC address for NAT networking...
    ==> node-02: Checking if box 'coreos-alpha' is up to date...
    ==> node-02: Setting the name of the VM: vagrant-k8s_node-02_1434009234652_71141
    ==> node-02: Fixed port collision for 22 => 2222. Now on port 2201.
    ==> node-02: Clearing any previously set network interfaces...
    ==> node-02: Preparing network interfaces based on configuration...
        node-02: Adapter 1: nat
        node-02: Adapter 2: hostonly
    ==> node-02: Forwarding ports...
        node-02: 22 => 2201 (adapter 1)
    ==> node-02: Running 'pre-boot' VM customizations...
    ==> node-02: Booting VM...
    ==> node-02: Waiting for machine to boot. This may take a few minutes...
        node-02: SSH address: 127.0.0.1:2201
        node-02: SSH username: core
        node-02: SSH auth method: private key
        node-02: Warning: Connection timeout. Retrying...
    ==> node-02: Machine booted and ready!
    ==> node-02: Setting hostname...
    ==> node-02: Configuring and enabling network interfaces...
    ==> node-02: Running provisioner: file...
    ==> node-02: Running provisioner: shell...
        node-02: Running: inline script
    ==> node-02: Running provisioner: file...
    ==> node-02: Running provisioner: file...
    ==> node-02: Running provisioner: shell...
        node-02: Running: inline script
    ==> node-02: Running triggers after up...
    ==> node-02: Waiting for Kubernetes minion [node-02] to become ready...
    $ source ~/.bash_profile 
    $ kubectl get svc
    NAME            LABELS                                    SELECTOR   IP(S)        PORT(S)
    kubernetes      component=apiserver,provider=kubernetes   <none>     10.100.0.2   443/TCP
    kubernetes-ro   component=apiserver,provider=kubernetes   <none>     10.100.0.1   80/TCP
    $ kubectl get pods
    POD       IP        CONTAINER(S)   IMAGE(S)   HOST      LABELS    STATUS    CREATED   MESSAGE
    $ DNS_UPSTREAM_SERVERS="172.17.42.1:53" USE_DOCKERCFG=true vagrant up --provider=virtualbox
    Bringing machine 'master' up with 'virtualbox' provider...
    Bringing machine 'node-01' up with 'virtualbox' provider...
    Bringing machine 'node-02' up with 'virtualbox' provider...
    ==> master: Running triggers before up...
    ==> master: Setting Kubernetes version 0.18.1
    ==> master: Configuring Kubernetes cluster DNS...
    ==> master: Checking if box 'coreos-alpha' is up to date...
    ==> master: VirtualBox VM is already running.
    ==> master: Running triggers after up...
    ==> master: Sanitizing stuff...
    Identity added: /home/tomasz.cichowicz/.vagrant.d/insecure_private_key (rsa w/o comment)
    ==> master: Installing kubectl for the kubernetes version we just bootstrapped...
    Downloading and installing linux version of 'kubectl' v0.18.1 into /usr/local/bin. This may take a couple minutes, depending on your internet speed..
    Setting environment variables..
    ==> master: Waiting for Kubernetes master to become ready...
    replicationcontrollers/kube-dns
    services/kube-dns
    ==> node-01: Checking if box 'coreos-alpha' is up to date...
    ==> node-01: VirtualBox VM is already running.
    ==> node-01: Running triggers after up...
    ==> node-01: Waiting for Kubernetes minion [node-01] to become ready...
    ==> node-02: Checking if box 'coreos-alpha' is up to date...
    ==> node-02: VirtualBox VM is already running.
    ==> node-02: Running triggers after up...
    ==> node-02: Waiting for Kubernetes minion [node-02] to become ready...
    $ kubectl get svc
    NAME            LABELS                                                              SELECTOR           IP(S)            PORT(S)
    kube-dns        k8s-app=kube-dns,kubernetes.io/cluster-service=true,name=kube-dns   k8s-app=kube-dns   10.100.198.131   53/UDP
                                                                                                                            53/TCP
    kubernetes      component=apiserver,provider=kubernetes                             <none>             10.100.0.2       443/TCP
    kubernetes-ro   component=apiserver,provider=kubernetes                             <none>             10.100.0.1       80/TCP
    $ kubectl get pods
    POD              IP            CONTAINER(S)   IMAGE(S)                                         HOST                        LABELS                                                STATUS    CREATED      MESSAGE
    kube-dns-rvkzh   10.244.61.2                                                                   172.17.8.103/172.17.8.103   k8s-app=kube-dns,kubernetes.io/cluster-service=true   Running   26 minutes   
                                   skydns         gcr.io/google_containers/skydns:2015-03-11-001                                                                                     Running   25 minutes   
                                   kube2sky       gcr.io/google_containers/kube2sky:1.7                                                                                              Running   26 minutes   
                                   etcd           gcr.io/google_containers/etcd:2.0.9                                                                                                Running   26 minutes   

I guess it boils down to this:

    ==> master: Waiting for Kubernetes master to become ready...
    The connection to the server localhost:8080 was refused - did you specify the right host or port?
    The connection to the server localhost:8080 was refused - did you specify the right host or port?

Why would Kubernetes master not be ready after 500 seconds (default timeout 50x 10s)?

**Comment by tcichowicz** [comment]
The problem is that each of the `system` statements in the Vagrantfile is executed in a separate subshell. This means that the environment variables are not being exported between calls, hence kubectl does not know the $KUBERNETES_MASTER address.

The easy solution is to add this variable to kubectl create calls, like this:

    system "KUBERNETES_MASTER=\"http://#{MASTER_IP}:8080\" kubectl create -f temp/dns-controller.yaml"

**Comment by pires** [comment]
Could you provide a PR?

**Comment by tcichowicz** [comment]
I'm working on it however at the moment I'm having problems with booting up the machines. I'll post when I know something more.

**Comment by tcichowicz** [comment]
This might not be the most elegant solution but I'm not proficient enough in ruby-shell integration to share environment variables between system calls.

I've had some problems running the alpha channel (CoreOS 709.0.0) but I've tested it on beta (695.0.0):

    $ vagrant destroy -f
    ==> node-02: Running triggers before destroy...
    ==> node-02: Forcing shutdown of VM...
    ==> node-02: Destroying VM and associated drives...
    ==> node-02: Running cleanup tasks for 'file' provisioner...
    ==> node-02: Running cleanup tasks for 'file' provisioner...
    ==> node-02: Running cleanup tasks for 'shell' provisioner...
    ==> node-01: Running triggers before destroy...
    ==> node-01: Forcing shutdown of VM...
    ==> node-01: Destroying VM and associated drives...
    ==> node-01: Running cleanup tasks for 'file' provisioner...
    ==> node-01: Running cleanup tasks for 'file' provisioner...
    ==> node-01: Running cleanup tasks for 'shell' provisioner...
    ==> master: Running triggers before destroy...
    ==> master: Forcing shutdown of VM...
    ==> master: Destroying VM and associated drives...
    ==> master: Running cleanup tasks for 'file' provisioner...
    ==> master: Running cleanup tasks for 'file' provisioner...
    ==> master: Running cleanup tasks for 'shell' provisioner...
    $ CHANNEL=beta vagrant up
    =============================================================================
    As this is a fastly evolving technology CoreOS' alpha channel is the only one
    expected to behave reliably. While one can invoke the beta or stable channels
    please be aware that your mileage may vary a whole lot.
    So, before submitting a bug, in this project, or upstreams (either kubernetes
    or CoreOS) please make sure it (also) happens in the (default) alpha channel.
    =============================================================================
    Bringing machine 'master' up with 'virtualbox' provider...
    Bringing machine 'node-01' up with 'virtualbox' provider...
    Bringing machine 'node-02' up with 'virtualbox' provider...
    ==> master: Running triggers before up...
    ==> master: Setting Kubernetes version 0.18.1
    ==> master: Configuring Kubernetes cluster DNS...
    ==> master: Box 'coreos-beta' could not be found. Attempting to find and install...
        master: Box Provider: virtualbox
        master: Box Version: >= 695.0.0
    ==> master: Loading metadata for box 'http://beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json'
        master: URL: http://beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
    ==> master: Adding box 'coreos-beta' (v695.0.0) for provider: virtualbox
        master: Downloading: http://beta.release.core-os.net/amd64-usr/695.0.0/coreos_production_vagrant.box
        master: Calculating and comparing box checksum...
    ==> master: Successfully added box 'coreos-beta' (v695.0.0) for 'virtualbox'!
    ==> master: Importing base box 'coreos-beta'...
    ==> master: Matching MAC address for NAT networking...
    ==> master: Checking if box 'coreos-beta' is up to date...
    ==> master: Setting the name of the VM: kubernetes-vagrant-coreos-cluster_master_1434103507059_8023
    ==> master: Clearing any previously set network interfaces...
    ==> master: Preparing network interfaces based on configuration...
        master: Adapter 1: nat
        master: Adapter 2: hostonly
    ==> master: Forwarding ports...
        master: 22 => 2222 (adapter 1)
    ==> master: Running 'pre-boot' VM customizations...
    ==> master: Booting VM...
    ==> master: Waiting for machine to boot. This may take a few minutes...
        master: SSH address: 127.0.0.1:2222
        master: SSH username: core
        master: SSH auth method: private key
        master: Warning: Connection timeout. Retrying...
    ==> master: Machine booted and ready!
    ==> master: Setting hostname...
    ==> master: Configuring and enabling network interfaces...
    ==> master: Running provisioner: file...
    ==> master: Running provisioner: file...
    ==> master: Running provisioner: shell...
        master: Running: inline script
    ==> master: Running triggers after up...
    ==> master: Sanitizing stuff...
    Identity added: /home/tomasz.cichowicz/.vagrant.d/insecure_private_key (rsa w/o comment)
    ==> master: Installing kubectl for the kubernetes version we just bootstrapped...
    Downloading and installing linux version of 'kubectl' v0.18.1 into /usr/local/bin. This may take a couple minutes, depending on your internet speed..
    Setting environment variables..
    ==> master: Waiting for Kubernetes master to become ready...
    replicationcontrollers/kube-dns
    services/kube-dns
    ==> node-01: Box 'coreos-beta' could not be found. Attempting to find and install...
        node-01: Box Provider: virtualbox
        node-01: Box Version: >= 695.0.0
    ==> node-01: Loading metadata for box 'http://beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json'
        node-01: URL: http://beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
    ==> node-01: Adding box 'coreos-beta' (v695.0.0) for provider: virtualbox
    ==> node-01: Importing base box 'coreos-beta'...
    ==> node-01: Matching MAC address for NAT networking...
    ==> node-01: Checking if box 'coreos-beta' is up to date...
    ==> node-01: Setting the name of the VM: kubernetes-vagrant-coreos-cluster_node-01_1434103653281_20597
    ==> node-01: Fixed port collision for 22 => 2222. Now on port 2200.
    ==> node-01: Clearing any previously set network interfaces...
    ==> node-01: Preparing network interfaces based on configuration...
        node-01: Adapter 1: nat
        node-01: Adapter 2: hostonly
    ==> node-01: Forwarding ports...
        node-01: 22 => 2200 (adapter 1)
    ==> node-01: Running 'pre-boot' VM customizations...
    ==> node-01: Booting VM...
    ==> node-01: Waiting for machine to boot. This may take a few minutes...
        node-01: SSH address: 127.0.0.1:2200
        node-01: SSH username: core
        node-01: SSH auth method: private key
        node-01: Warning: Connection timeout. Retrying...
    ==> node-01: Machine booted and ready!
    ==> node-01: Setting hostname...
    ==> node-01: Configuring and enabling network interfaces...
    ==> node-01: Running provisioner: file...
    ==> node-01: Running provisioner: file...
    ==> node-01: Running provisioner: shell...
        node-01: Running: inline script
    ==> node-01: Running triggers after up...
    ==> node-01: Waiting for Kubernetes minion [node-01] to become ready...
    ==> node-02: Box 'coreos-beta' could not be found. Attempting to find and install...
        node-02: Box Provider: virtualbox
        node-02: Box Version: >= 695.0.0
    ==> node-02: Loading metadata for box 'http://beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json'
        node-02: URL: http://beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
    ==> node-02: Adding box 'coreos-beta' (v695.0.0) for provider: virtualbox
    ==> node-02: Importing base box 'coreos-beta'...
    ==> node-02: Matching MAC address for NAT networking...
    ==> node-02: Checking if box 'coreos-beta' is up to date...
    ==> node-02: Setting the name of the VM: kubernetes-vagrant-coreos-cluster_node-02_1434103754882_6461
    ==> node-02: Fixed port collision for 22 => 2222. Now on port 2201.
    ==> node-02: Clearing any previously set network interfaces...
    ==> node-02: Preparing network interfaces based on configuration...
        node-02: Adapter 1: nat
        node-02: Adapter 2: hostonly
    ==> node-02: Forwarding ports...
        node-02: 22 => 2201 (adapter 1)
    ==> node-02: Running 'pre-boot' VM customizations...
    ==> node-02: Booting VM...
    ==> node-02: Waiting for machine to boot. This may take a few minutes...
        node-02: SSH address: 127.0.0.1:2201
        node-02: SSH username: core
        node-02: SSH auth method: private key
        node-02: Warning: Connection timeout. Retrying...
    ==> node-02: Machine booted and ready!
    ==> node-02: Setting hostname...
    ==> node-02: Configuring and enabling network interfaces...
    ==> node-02: Running provisioner: file...
    ==> node-02: Running provisioner: file...
    ==> node-02: Running provisioner: shell...
        node-02: Running: inline script
    ==> node-02: Running triggers after up...
    ==> node-02: Waiting for Kubernetes minion [node-02] to become ready...
    $ source ~/.bash_profile 
    $ kubectl get pods
    POD              IP            CONTAINER(S)   IMAGE(S)                                         HOST                        LABELS                                                STATUS    CREATED     MESSAGE
    kube-dns-7w79u   10.244.33.2                                                                   172.17.8.102/172.17.8.102   k8s-app=kube-dns,kubernetes.io/cluster-service=true   Running   4 minutes   
                                   etcd           gcr.io/google_containers/etcd:2.0.9                                                                                                Running   2 minutes   
                                   skydns         gcr.io/google_containers/skydns:2015-03-11-001                                                                                     Running   2 minutes   
                                   kube2sky       gcr.io/google_containers/kube2sky:1.7                                                                                              Running   2 minutes
