### ISSUE TITLE
Error configuring network.

### ISSUE THREAD

**Issue by tslater** [pires/kubernetes-vagrant-coreos-cluster#107]
Things were working fine until one time I tried to load the cluster and things went awry.
SSH failed and so I set the username manually in the Vagrantfile to core.

Now I get this error
````
==> master: Setting hostname...
==> master: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
ifconfig  172.17.8.101 netmask 255.255.255.0
Stdout from the command:

Stderr from the command:
SIOCSIFNETMASK: No such device
````

I've seen advice along these lines:
https://muffinresearch.co.uk/vmware-siocsifaddr-no-such-device-eth0-after-cloning/
...I have not done any cloning though.

I've tried 
````
sudo systemctl restart systemd-networkd
````
but no cigar.

**Comment by tslater** [comment]
Interesting update: calling ```vagrant up``` instead of ```vagrant reload``` let me get past the master node and node  01, but got the same error on node 02. Running ```vagrant up``` again let me clear node 03. But I still can't reload without getting that error on master.

**Comment by pires** [comment]
I have no way to replicate this since I have no VMware. @windwizard @capttofu care to comment?

**Comment by CaptTofu** [comment]
I’m trying to think of a way you could… I think fusion or workstation might have a trial period. Not sure.

**Comment by tslater** [comment]
Sorry if it was unclear from the link...I'm using virtualbox

**Comment by tslater** [comment]
I tried rebuilding from the latest code and now I get this on master:

````
Jun 03 21:15:42 master wget[2557]: 2015-06-03 21:15:42 (11.9 MB/s) - '/opt/bin/kube-apiserver.100' saved [35114024/35114024]
Jun 03 21:15:42 master systemd[1]: Started Kubernetes API Server.
Jun 03 21:15:42 master kube-apiserver[2581]: I0603 21:15:42.064868    2581 plugins.go:69] No cloud provider specified.
Jun 03 21:15:42 master systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 03 21:15:42 master systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 03 21:15:42 master systemd[1]: kube-apiserver.service failed.
Jun 03 21:15:42 master kube-apiserver[2581]: F0603 21:15:42.065707    2581 server.go:317] Invalid Authentication Config: open /tmp/kube-serviceaccount.key: no such file or directory
```

**Comment by tslater** [comment]
Also:

```
Jun 03 22:41:03 master etcdctl[723]: Error:  cannot sync with the cluster using endpoints http://127.0.0.1:4001, http://127.0.0.1:2379
Jun 03 22:41:03 master systemd[1]: flanneld.service: control process exited, code=exited status=2
Jun 03 22:41:03 master systemd[1]: Failed to start Network fabric for containers.
Jun 03 22:41:03 master systemd[1]: Unit flanneld.service entered failed state.
Jun 03 22:41:03 master systemd[1]: flanneld.service failed.
Jun 03 22:41:03 master fleetd[704]: INFO client.go:292: Failed getting response from http://localhost:4001/: read tcp 127.0.0.1:4001: connection reset by peer
Jun 03 22:41:03 master fleetd[704]: INFO client.go:292: Failed getting response from http://localhost:2379/: dial tcp 127.0.0.1:2379: connection refused
Jun 03 22:41:03 master fleetd[704]: ERROR client.go:214: Unable to get result for {Update /_coreos.com/fleet/machines/90a958daef8e431a8b8084be6866ea1c/object}, retrying in 100ms
Jun 03 22:41:03 master systemd[1]: etcd2.service: main process exited, code=exited, status=1/FAILURE
Jun 03 22:41:03 master systemd[1]: Unit etcd2.service entered failed state.
Jun 03 22:41:03 master systemd[1]: etcd2.service failed.
```

**Comment by pires** [comment]
I'm sorry but definitely there's something very wrong with your cluster. Which version of Vagrant and Virtualbox are you using?

Please clone the repository again to make sure there is nothing wrong with the files or any changes that I can't support and run:
```
vagrant destroy -f
vagrant up
```

After all is done check again.

**Comment by tslater** [comment]
I'm on Virtualbox 4.3.28 r100309
and Vagrant 1.7.2

I have destroyed and cloned half a dozen times today....
I think it's related to the /tmp/files_that_are_here being destroyed. I get the error after my first reload.

I also get errors like this:
```
Jun 03 23:17:26 master systemd-udevd[386]: starting version 219
Jun 03 23:17:26 master systemd-udevd[386]: RUN{builtin}: 'uaccess' unknown /usr/lib64/udev/rules.d/73-seat-late.rules:15
```

That I don't understand...but I do think the /tmp/kube-serviceaccount.key file is a big deal since it's not there. I tried writing it to another location besides /tmp/ but I failed...I don't know Vagrant or even Ruby very well.

**Comment by pires** [comment]
Ah I do not support reload yet. Sorry.

**Comment by tslater** [comment]
I have issues sometimes where one machine reboots or stops or something. Or times where i need to mount new directories. How can I bring the cluster in a consistent state. Reload doesn't work. Up is really slow and usually doesn't work. The whole thing is rather fragile...Is there a good work around?

**Comment by pires** [comment]
@tslater I feel your pain but I don't grok Vagrant enough to understand what `reload` actually does. Would you like to give a take on this an provide a PR? I'd be happy to review it.

**Comment by CaptTofu** [comment]
Greetings -sorry I haven’t responded - I have been traveling, AnsibleFest… I will reply soon.

**Comment by AntonioMeireles** [comment]
**reload** is reasonably simple to handle - is a matter of elegantly turn it into a halt / start sequence. (i think can get it right over next week in my tree and then @pires can cherry pick).
suspend/**resume** is trickiest, not exactly because vagrant per se but because it is not simple to predict how things will behave when they spot XXL time gaps in VM clocks. i guess the sanest/simplest/most reliable way to handle it is just treat a suspend like an halt, and a resume like a plain vagrant up... but that's me - toughts on this one ?

**Comment by AntonioMeireles** [comment]
guys, @pires look at at above commit plz & report back...

**Comment by pires** [comment]
Thanks @AntonioMeireles that should prevent users from trying this and messing with their cluster.

**Comment by AntonioMeireles** [comment]
@tslater can you confirm that above patch that got merged fixes things for you please ?

**Comment by pires** [comment]
@AntonioMeireles @tslater this doesn't fix it, but instead just doesn't allow you to run `reload`.

Yet @tslater says `up` is slow and doesn't work but to me it's just a random rant without added value for this issue. `up` works alright. And I'm always open to PRs more than I'm open to rants.

**Comment by tslater** [comment]
@pires, that's kind of rude for you to call it a rant, don't you think? I've destroyed rebuilt the cluster tons of times and that's the only way I can make changes to it. I've tried all kinds of halt, suspends, reloads etc. and every time my whole cluster breaks and I have to rebuild it. There was no warning on the README for this. It's going to take me time to learn vagrant and the innards of running all this. Apparently you don't understand it enough to fix it but please don't insult me and call the issues with your software rants. I'm trying to be helpful.

**Comment by pires** [comment]
> I've tried all kinds of halt, suspends, reloads etc. and every time my whole cluster breaks and I have to rebuild it. From what I understand it's broken and I get that it isn't fixed.

One thing is to open an issue describing a situation, another thing is saying "it's broken", and another thing is to provide PRs. I'm not a Vagrant expert, or a Kubernetes expert. This is something made to ease the life of others - more than mine now that I'm not using this as much as I did in the past - and not support every scenario on Earth. I'm open to contributions. Always have been.

> please don't insult me

I just said it's a rant. Saying "it's broken" is a very bold statement. No insults here.

> Can't we work through this together?

Of course we can. You could research each issue, and provide logs for each one of them. I didn't understand you were `reload`ing until 4 days after you opened the issue.

`reload` is not supported as we speak but I'm open to PRs changing that in a proper way. I unfortunately do not have the time or will to do it.

Can I suggest that you remove Docker cache? It will make `up` much more fast.

**Comment by pires** [comment]
You can try reload now as per #112

**Comment by CaptTofu** [comment]
Hi all,

Finally had time to try things out. I still, with the most current, have DNS end up failing running this using vmware_fusion. It worked at first, then stopped. Adding entries to resolve.conf doesn’t work because it gets overwritten sytstemd-resolved with a file with “no nameservers found” on both the master and nodes.

Regards,

Patrick
