### ISSUE TITLE
Drop CoreOS stable support

### ISSUE THREAD

**Issue by pires** [pires/kubernetes-vagrant-coreos-cluster#11]
@AntonioMeireles just saw references to the CoreOS stable channel but we should actually not support it. For instance, the ```-s=overlay``` Docker option is not supported in Docker < 1.4.x and I had a lot of issues because of that with stable users. And yes, right now, stable is using Docker 1.4.1 but I'd really like to not hold on to that premise.

**Comment by AntonioMeireles** [comment]
ah, ok. will fix that in a bit.
