### ISSUE TITLE
SkyDNS appears to be segregated from CoreOS's etcd?

### ISSUE THREAD

**Issue by sporkmonger** [pires/kubernetes-vagrant-coreos-cluster#110]
You're currently spinning up an etcd container for SkyDNS, which doesn't appear to be talking to the main etcd instances that CoreOS runs. And I'm not sure I understand why you'd want to do that?

**Comment by pires** [comment]
@sporkmonger it's common practice in the Kubernetes world. `etcd` is a requirement for `skydns` but in the future won't be a requirement for Kubernetes. Also, until recently, the `etcd` version bundled with CoreOS was not supported by `skydns`.

**Comment by sporkmonger** [comment]
Interesting. I hadn't seen that done before – I tried looking around for other examples though and didn't find any. Got any pointers to projects or posts that better explain the rationale?

**Comment by sporkmonger** [comment]
The other thing I'm seeing is that nslookup seems to work fine w/ SkyDNS if you `exec` your way into the SkyDNS container, but trying to run nslookup through the DNS service's portal IP seems to give `nslookup: can't resolve 'skydns.local'`?

**Comment by pires** [comment]
@sporkmonger https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons/dns

Not sure what a toolbox container is, but for access said DNS you need to _be_ a pod container.

**Comment by sporkmonger** [comment]
`toolbox` on the CoreOS host command line boots a toolbox container.

**Comment by sporkmonger** [comment]
OK, so inside a pod container you'd have DNS, gotcha, but one last thing I'm not sure I'm understanding here – you segregate etcd from the CoreOS host, but are you running a separate set of etcd silos for every service that needs to talk to etcd?

**Comment by sporkmonger** [comment]
I guess not really one last thing – `kube2sky` is pushing service metadata into etcd I assume, but what about things that aren't managed by Kubernetes that need to advertise themselves w/ SkyDNS? (e.g. something that needs a perfect one-per-host anti-affinity guarantee that Kubernetes can't make, as far as I know.) They wouldn't live inside that pod, so I'm not sure how exactly you'd go about publishing a service advertisement into a segregated etcd set, since you can't just point to `localhost`?

**Comment by sporkmonger** [comment]
(Also sorry for all the questions! :-) )

**Comment by pires** [comment]
> you segregate etcd from the CoreOS host

What? No. I only use a different `etcd` for the DNS pod, same way as upstream project.

> but what about things that aren't managed by Kubernetes that need to advertise themselves

Use each node `etcd` instance. Or deploy your own pod or external cluster and use it.

**Comment by sporkmonger** [comment]
Hmm, when I query the pod etcd it doesn't have any of the keys of the host etcd?

**Comment by pires** [comment]
You are very confused. Forget about the `etcd` that DNS pod uses. Never use it! Make your apps the way you want to.

**Comment by sporkmonger** [comment]
Haha, FWIW, that's what I already ended up doing – was trying to understand why you'd done it this way though.

**Comment by pires** [comment]
Read my first comment.
