### ISSUE TITLE
OpenStack provider

### ISSUE THREAD

**Issue by jdojff** [pires/kubernetes-vagrant-coreos-cluster#111]
Would it be possible to update configuration to run kubernetes cluster on OpenStack instances using plugin like: https://github.com/cloudbau/vagrant-openstack-plugin ?

**Comment by pires** [comment]
@jdojff it is possible, but I would need someone with access to an OpenStack install to actually implement and test it.

**Comment by jdojff** [comment]
Well, I have an account at cloud provider, not sure about implementation, but I could test it there.

**Comment by pires** [comment]
Idle.
