### ISSUE TITLE
Add support for vagrant reload

### ISSUE THREAD

**Issue by pires** [pires/kubernetes-vagrant-coreos-cluster#112]
Some people have been asking for better `vagrant reload` support (and `halt` and `resume`), but given the nature of Kubernetes components, and my lack of Vagrant skills, I need more enlightened action here.

Refs #107

**Comment by AntonioMeireles** [comment]
@pires shoudn't this be closed already via above commit ?

**Comment by pires** [comment]
@AntonioMeireles it's just a workaround. I'd really like to see this implemented in a way that would work for everyone.

**Comment by AntonioMeireles** [comment]
humm... 

can you test drive the patch bellow please ? it's a (very) cheap hack ... but at sight seems to work (not merged in my tree yet)... 

```patch 
diff --git a/Vagrantfile b/Vagrantfile
index 99c92fc..b1f49e2 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -217,10 +217,9 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
         info "'vagrant suspend' and 'vagrant resume' are disabled."
         info "- please do use 'vagrant halt' and 'vagrant up' instead."
       end
-      # simpler / more reliable
-      kHost.trigger.reject :reload do
-        info "'vagrant reload' is disabled."
-        info "- please do use 'vagrant halt' and 'vagrant up' instead."
+      config.trigger.instead_of :reload do
+        exec "vagrant halt && vagrant up"
+        exit
       end
 
       # vagrant-triggers has no concept of global triggers so to avoid having
```

**Comment by pires** [comment]
This feels misleading. I much prefer to have it explicitly blocked. Thank you, nonetheless.

**Comment by AntonioMeireles** [comment]
misleading in what sense (curious) ? 
```
Command: vagrant reload

The equivalent of running a halt followed by an up.
```
(from the official docs [here](http://docs.vagrantup.com/v2/cli/reload.html))

**Comment by pires** [comment]
Sorry, you're right. Mondays... I read it correctly, but my mind interpreted `destroy` instead of `halt`. Will do that and close this.
