### ISSUE TITLE
kubernetes fails to start on second boot

### ISSUE THREAD

**Issue by hjfreyer** [pires/kubernetes-vagrant-coreos-cluster#115]
Steps to reproduce:
1. `vagrant destroy master`
2. `vagrant up master`
3. Wait for start, make sure all is good.
4. `vagrant halt master`
5. Reboot host machine (probably irrelevant, but including because I did it).
6. `vagrant up master`

The API server never comes up. Checking the journal, I see this (emphasis added):

-- Logs begin at Sun 2015-06-07 18:30:34 UTC, end at Sun 2015-06-07 19:17:21 UTC. --
Jun 07 19:17:21 master wupiao[7742]: .
Jun 07 19:17:21 master wupiao[7732]: .
Jun 07 19:17:20 master wupiao[7742]: .
Jun 07 19:17:20 master wupiao[7732]: .
Jun 07 19:17:19 master wupiao[7742]: .
Jun 07 19:17:19 master wupiao[7732]: .
Jun 07 19:17:18 master wupiao[7742]: .
Jun 07 19:17:18 master wupiao[7732]: .
Jun 07 19:17:17 master wupiao[7732]: .
Jun 07 19:17:17 master wupiao[7742]: .
Jun 07 19:17:16 master wupiao[7742]: .
Jun 07 19:17:16 master wupiao[7732]: .
Jun 07 19:17:15 master wupiao[7742]: .
Jun 07 19:17:15 master systemd[1]: kube-apiserver.service failed.
Jun 07 19:17:15 master systemd[1]: Unit kube-apiserver.service entered failed state.
Jun 07 19:17:15 master systemd[1]: kube-apiserver.service: main process exited, code=exited, status=255/n/a
Jun 07 19:17:15 master wupiao[7732]: .
Jun 07 19:17:15 master kube-apiserver[8140]: F0607 19:17:15.883180    8140 server.go:317] **Invalid Authentication Config: open /tmp/kube-serviceaccount.key: no such file or directory**
Jun 07 19:17:15 master kube-apiserver[8140]: I0607 19:17:15.882384    8140 plugins.go:69] No cloud provider specified.

**Comment by hjfreyer** [comment]
I reset to c788f584224c2da2555e2468eb75c45c0e3cf14b and the problem seems to have gone away.

**Comment by pires** [comment]
Yes, because of https://github.com/pires/kubernetes-vagrant-coreos-cluster/commit/3bc7b3dc63f4a2d84b39a6e7aebed35460ddfa06. PR on the way, thank you for reporting @hjfreyer.
