### ISSUE TITLE
vagrant up fails with coreos 709.0.0

### ISSUE THREAD

**Issue by ilidiomartins** [pires/kubernetes-vagrant-coreos-cluster#123]
```vagrant up``` fails with coreos 709.0.0 (works ok with 695).

```
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2222
    master: SSH username: core
    master: SSH auth method: private key
    master: Warning: Connection timeout. Retrying...
==> master: Machine booted and ready!
==> master: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

systemctl start system-cloudinit@-var-tmp-hostname.yml.service

Stdout from the command:



Stderr from the command:

Job for system-cloudinit@-var-tmp-hostname.yml.service failed because a configured resource limit was exceeded. See "systemctl status system-cloudinit@-var-tmp-hostname.yml.service" and "journalctl -xe" for details.
```

**Comment by AntonioMeireles** [comment]
humm. you are using virtualbox or paralells ?

**Comment by ilidiomartins** [comment]
virtualbox

**Comment by AntonioMeireles** [comment]
strange. i 've hit that this morning with my custom parallels boxes **before** fixing my code to consume latest upstream. it seems that latest upstream [fixes](https://github.com/coreos/coreos-overlay/commit/db5e760240000f7451d24218ef565d83e01900ea) aren't in 709.0.0 so things break.

in the meantime just use my AntonioMeireles/coreos-alpha box (it has the fix and also has a virtualbox flavour).

**Comment by pires** [comment]
Other people like are reporting this as well. Will look into it as soon as I get back behind the computer.

**Comment by AntonioMeireles** [comment]
my box work :smile: in the meantime

**Comment by AntonioMeireles** [comment]
the issue is system related. absolute paths for systemd unit templates shouldn't start anymore by - (/). (they should be the ouptut of `systemd-escape -p ${PATH}`). in practice one just has to cut 1st char.

**Comment by pires** [comment]
The usage of `-` means if that execution fails, continue with unit instructions.

**Comment by AntonioMeireles** [comment]
@pires no,no. different stuff...
that is when you have something like ... Exec=-something

the issue here is the first '-' in `system-cloudinit@-var-tmp-hostname.yml.service`. it must be now `system-cloudinit@var-tmp-hostname.yml.service`

**Comment by pires** [comment]
Unable to fix this until Monday. Care to make a pr @antoniomeireles?

**Comment by AntonioMeireles** [comment]
```patch
diff --git a/Vagrantfile b/Vagrantfile
index cbbe3dc..8c3b3e7 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -143,7 +143,13 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
       override.vm.box_url = "#{upstream}/coreos_production_vagrant_vmware_fusion.json"
     end
   end
-
+  # just UNTIL pires/kubernetes-vagrant-coreos-cluster#123
+  # (coreos/bugs#385) isn't sorted...
+  config.vm.provider :virtualbox do |vb, override|
+    override.vm.box = "AntonioMeireles/coreos-#{CHANNEL}"
+    override.vm.box_url = "https://vagrantcloud.com/AntonioMeireles/coreos-#{CHANNEL}"
+  end
+  #/
   config.vm.provider :parallels do |vb, override|
     override.vm.box = "AntonioMeireles/coreos-#{CHANNEL}"
     override.vm.box_url = "https://vagrantcloud.com/AntonioMeireles/coreos-#{CHANNEL}"
```

guys, try this plz.

**Comment by ilidiomartins** [comment]
yep, that's working for me

**Comment by hjfreyer** [comment]
`CHANNEL=beta vagrant up` also works.

**Comment by AntonioMeireles** [comment]
@hjfreyer, the issue **only** affects 709.0.0. no need to do/mod anything if you 're consuming the stable or beta channels.

**Comment by hjfreyer** [comment]
Indeed. What I meant was, I'm normally on alpha, but I've switched to beta as a workaround until this gets fixed.

**Comment by ashic** [comment]
I'm running it from powershell, and

```
$env:CHANNEL = "beta"
```

is working for me too.

**Comment by pires** [comment]
`beta` channel is now the default until upstream fixes this and cuts a new release.
