### ISSUE TITLE
Ability to specify DOCKER_OPTS

### ISSUE THREAD

**Issue by josephschorr** [pires/kubernetes-vagrant-coreos-cluster#129]
The ability to specify `DOCKER_OPTS` as an env var on the `vagrant up` command and have it be passed to the virtual machines is very useful for adding params such as `insecure-registry` for local testing.

**Comment by pires** [comment]
@josephschorr you should thank @tcichowicz!

**Comment by josephschorr** [comment]
@tcichowicz: Thanks for doing this!

**Comment by tcichowicz** [comment]
No problem, hope this helps :)
