### ISSUE TITLE
Use local docker images for pods

### ISSUE THREAD

**Issue by tdeheurles** [pires/kubernetes-vagrant-coreos-cluster#132]
hi, 

I'm starting to use your project for local test (before pushing to gke).
The way I go is :
- starting your cluster
- nfs my projects
- vagrant ssh in master
- creating docker images locally

But when I create my pod, I receive this message :
`Error: image library/servicename:localbuild.0.0.1 not found`

The image is on the master, and the node don't look at this point.

Is the private registry the only way to make my docker images available to other nodes ?
Maybe I need to remove other node and make kubernetes run on only one VM.
I don't like that way because it will use lot of disk space in addtion to complicate for simple local test ...

You're pointing to DOCKERCFG and maybe the solution is trivial, that's why I make an issue.

**Comment by pires** [comment]
The `registry` running on `master` can only be used as a cache and not as a local registry where you publish your images.

**Comment by pires** [comment]
Stalled.
