### ISSUE TITLE
remove/deprecate DOCKERCFG & USE_DOCKERCFG env vars in respect to kubernetes v1.0?

### ISSUE THREAD

**Issue by MaxDaten** [pires/kubernetes-vagrant-coreos-cluster#136]
kubernetes introduced [imagePullSecrets](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/images.md#specifying-imagepullsecrets-on-a-pod) to store custom dockercfg in k8s secrets. I tried it, and it works flawless for me.

The removal of these vars would reduce complexity of the Vagrantfile and avoids the fiddling with the k8s nodes' filesystem.

**Comment by pires** [comment]
@MaxDaten will you provide a PR?

**Comment by pires** [comment]
Stalled.
