### ISSUE TITLE
Troubleshooting section suggestion

### ISSUE THREAD

**Issue by vsimon** [pires/kubernetes-vagrant-coreos-cluster#139]
I just ran into closed issue #127 on my mac. The solution to delete my ~/.kube/config worked. It would be nice to have a section documenting such gems that may get buried in the closed issues section.

**Comment by pires** [comment]
@vsimon you are very right, since I have suggested that to more people having that issue than I can count. Could it be your first PR? Let me know ;)

**Comment by vsimon** [comment]
Sure, I'd be happy to.

I just opened:
https://github.com/pires/kubernetes-vagrant-coreos-cluster/pull/140

**Comment by pires** [comment]
Awesome, thank you @vsimon!
