### ISSUE TITLE
Can't Running Kubernetes locally via Docker

### ISSUE THREAD

**Issue by BlueShells** [pires/kubernetes-vagrant-coreos-cluster#141]
I followed this 

http://kubernetes.io/v1.0/docs/getting-started-guides/docker.html

but ,after I done step 3,I download the kubectl,but when I run  './kubectl get node'
I get this message:

'The connection to the server localhost:8080 was refused - did you specify the right host or port?'

why this happened?I am running it on 'Red Hat Enterprise Linux Server release 7.1'

here is the info：

[root@openshift-v3 yum.repos.d]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[root@openshift-v3 yum.repos.d]# docker run --net=host -d gcr.io/google_containers/etcd:2.0.9 /usr/local/bin/etcd --addr=127.0.0.1:4001 --bind-addr=0.0.0.0:4001 --data-dir=/var/etcd/data
8a49abb807f4264e62da3dfa9972e8d731a8d365ade2d79d8f6dcf4c2e3f8cf1
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
[root@openshift-v3 yum.repos.d]# docker run --net=host -d -v /var/run/docker.sock:/var/run/docker.sock  gcr.io/google_containers/hyperkube:v0.21.2 /hyperkube kubelet --api_servers=http://localhost:8080 --v=2 --address=0.0.0.0 --enable_server --hostname_override=127.0.0.1 --config=/etc/kubernetes/manifests
b5b7d7ab4059ef807a073cde182e71ca7f754c6c965174759821bd0af90f6d0f
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
[root@openshift-v3 yum.repos.d]# docker run -d --net=host --privileged gcr.io/google_containers/hyperkube:v0.21.2 /hyperkube proxy --master=http://127.0.0.1:8080 --v=2
f13a7851a5f1b089118d4228b66023827cb6a6ec6c4fb4913efe75e26c1568e7
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
[root@openshift-v3 yum.repos.d]# docker ps
CONTAINER ID        IMAGE                                        COMMAND                CREATED             STATUS              PORTS               NAMES
f13a7851a5f1        gcr.io/google_containers/hyperkube:v0.21.2   "/hyperkube proxy --   6 seconds ago       Up 5 seconds                            insane_rosalind     
b5b7d7ab4059        gcr.io/google_containers/hyperkube:v0.21.2   "/hyperkube kubelet    17 seconds ago      Up 16 seconds                           romantic_jang       
8a49abb807f4        gcr.io/google_containers/etcd:2.0.9          "/usr/local/bin/etcd   41 seconds ago      Up 40 seconds                           pensive_brattain    
[root@openshift-v3 yum.repos.d]#

[root@openshift-v3 yum.repos.d]# ./kubectl get node
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by BlueShells** [comment]
this can be fixed by 

setenforce 0

the selinux caused this problem

**Comment by pires** [comment]
I'm sorry but this seems to be totally unrelated to this project.
