### ISSUE TITLE
bridged interface for off host contact?

### ISSUE THREAD

**Issue by drocsid** [pires/kubernetes-vagrant-coreos-cluster#143]
How about a bridged configuration (at least that's what it's called in virtual box) so we could connect to services off the virtual machine host. Furthermore, with bridging, we would be able to connect to virtual machines running on other hosts. Have you attempted using bridged interfaces, or is there another approach I'm not aware of?

**Comment by pires** [comment]
You can access the VM ip addresses, can you not? Ofc, this is available only on each host. Glad to review a PR, if any.

**Comment by drocsid** [comment]
I'm fiddling with it. I'll be on #freenode if you have a minute.

**Comment by pires** [comment]
Look for me, I'm `ppires`. I'll probably be around tomorrow if not today.

**Comment by drocsid** [comment]
As per my comments on IRC:

1. motivation is connecting to services off the vm provider host and creating nodes on external host vm
2. Double NAT might work (NAT for incomming packets on vm provider host), but bridging is preferred 
3. From my limited understanding, I think flannel won't work well with a bridged interface, since IPs assignment will need to change 
4. It might be possible to at least add an extra bridged interface for off site services. 

These are my findings, not necessarily correct. Posted here in case anyone else is interested.

**Comment by tdeheurles** [comment]
There is a little implementation to do for going in the bridge way.

I have done it in [homecores](https://github.com/tdeheurles/homecores) (like a copy of that one but with the idea to have only one VM on each host). 

The `pires/kubernetes-vagrant-coreos-cluster` project is a great introduction to kubernetes. Hard to do better than :
```
git clone ...
vagrant up ...
```

If we use bridge, we will have to deal with the selection of the bridge interface when there is more than one on the host. I didn't find a good satifying way to do that for now. I need to use the Virtualbox command : `vboxmanage list bridgedifs`. But `vboxmanage` isn't added in the PATH with the virtualbox installer (maybe different for linux/osx).
So you need to find it or ask the user to do it ... I didn't try to do that as it can be installed on so many different kinf of `host`.

I feel that this project is really great to do his job of `tutorial`.

But if we find a way to automate the bridge part, it could be great ^^

**Comment by pires** [comment]
I agree with @tdeheurles. Thank you @drocsid for reporting but am closing since there's no one interested in providing a PR which I can review. Reopen if otherwise.
