### ISSUE TITLE
Vagrant up unable to connect on SSH with CoreOS alpha channel

### ISSUE THREAD

**Issue by mrsheepuk** [pires/kubernetes-vagrant-coreos-cluster#146]
I've not been able to work out why, but using the default alpha channel for CoreOS, doing a vagrant up gets as far as "Waiting for machine to boot" then is never able to connect on SSH to the master. It retries 15 or so times then gives up. I can see in Virtualbox that the console is up and running, but SSH cannot connect. Attempting to manually SSH to the IP/port (e.g. 127.0.0.1 port 2222) also cannot connect.

I changed the channel to beta, and it worked first time with no problems.

I'm using Ubuntu 15.04 with Virtualbox 4.3.28, and I'm behind a web proxy (although I think this is earlier in the boot process than any web access, so I don't believe that is getting involved).

**Comment by mrsheepuk** [comment]
The CoreOS alpha version that Vagrant pulled down was 758.1.0.

**Comment by pires** [comment]
Can you retry with `alpha`? This was probably something with Virtualbox networking.

**Comment by mrsheepuk** [comment]
Tried again right now, same result. I've tried several times; I don't know if it's something to do with my particular network configuration. Here's the full vagrant up command I have run:

    NODE_MEM=1024 BASE_IP_ADDR=192.168.100 DNS_UPSTREAM_SERVERS=10.84.1.103:53 vagrant up

The DNS server is correct and working, and the BASE_IP_ADDR isn't conflicting with anything else on my machine (I can ping 192.168.100.101 successfully once master is up, it just can't complete the SSH connection).

**Comment by pires** [comment]
Thank you for reporting. Let me take a look..

**Comment by pires** [comment]
I cannot reproduce this.

**Comment by mrsheepuk** [comment]
I'll give it a go from a different environment and see if I can work out whether it's something to do with my machine. Will report back tomorrow when I've had a chance to do that.

**Comment by mrsheepuk** [comment]
I've just tried a plain 

    vagrant init coreos-alpha 
    vagrant up

... and I get the same result, so I think it's something environmental with the CoreOS base box and my setup, rather than a problem with kubernetes-vagrant-coreos-cluster specifically. I'll keep digging to see if I can feed anything back to you, but I suspect I need to raise this with coreos-vagrant instead.

**Comment by pires** [comment]
```
$ vagrant init coreos-alpha
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'coreos-alpha'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'coreos-alpha' is up to date...
==> default: Setting the name of the VM: pires_default_1438770754004_37376
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: core
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
```

**Comment by pires** [comment]
I even set `config.vm.box_check_update = true` on `Vagrantfile`.

**Comment by pires** [comment]
```
$ ls .vagrant.d/boxes/coreos-alpha |grep 758
758.1.0
```

**Comment by mrsheepuk** [comment]
Thanks for trying that - it looks certain that it's something to do with my host environment. I'll report back when I find out what is causing this!

**Comment by pires** [comment]
@mrsheepuk have you rebooted your machine? Or just the `virtualbox` daemon? It may be something related to the networking.

**Comment by mrsheepuk** [comment]
Rebooted the machine, upgraded Virtualbox to 5.0, upgraded Vagrant to 1.7.4, still getting identical behavior. It's very strange! I have a vague suspicion it may be something to do with a reverse-DNS lookup on the source IP of the SSH connection timing out / failing, but I can't work out how to prove that.

**Comment by pires** [comment]
```
rm -rf ~/.vagrant.d/boxes
vagrant init coreos-alpha
vagrant up
```

Could it be something related to any DHCP server on your network setting different VM ip addresses?

**Comment by mrsheepuk** [comment]
Think I've found the problem - it was this entry in my iptables config (added, I believe, by a local docker install):

```
Chain POSTROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    MASQUERADE  all  --  172.17.0.0/16        0.0.0.0/0      
```

Removed that and I can now boot a clean coreos-alpha. Going back to try the kubernetes-vagrant-coreos cluster again now.

**Comment by pires** [comment]
Awesome @mrsheepuk! Glad that you're keeping up with it :+1: let me know.

**Comment by isobina** [comment]
Hi, I'm having the same issue on my ubuntu server 14.04. iptables are all clear, no firewalls, nothing. Any ideas ?
