### ISSUE TITLE
Would you accept a pull request adding Ceph?

### ISSUE THREAD

**Issue by PurpleBooth** [pires/kubernetes-vagrant-coreos-cluster#148]
Or is that out of scope for the aim of this project?

**Comment by pires** [comment]
Can you develop further and explain what is the reasoning behind that and what would be the _gains_ from it?

**Comment by PurpleBooth** [comment]
The gains from it are basically that we have a node agnostic way to fulfil
volume claims on vagrant that we would normally fill with GCE network
disks, or the amazon equivalents.

On Wed, 19 Aug 2015 16:53 Paulo Pires <notifications@github.com> wrote:

> Can you develop further and explain what is the reasoning behind that and
> what would be the *gains* from it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pires/kubernetes-vagrant-coreos-cluster/issues/148#issuecomment-132646721>
> .
>
-- 
Billie Thompson
Software Developer
Purple Booth Ltd

Mob: 07813452516
Web: purplebooth.co.uk
Keybase: <http://billie.codes/1NOw29c>
LinkedIn: <http://billie.codes/1KT8gcI>
Twitter: <http://billie.codes/1SGPMCw>

**Comment by pires** [comment]
@PurpleBooth it's still not clear to me what would be the gains, since this is mostly used for development purposes. Would it be optional? Would it be _free_, in the sense of configuring everything needed and not consume too much resources, for any user?
I am aware of Ceph but never seen it outside of datacenters.

**Comment by PurpleBooth** [comment]
I'll have a look at the configuration I'm currently using, and see if the
usage is particularly high resource wise tomorrow and report back!

It's easy to turn off and on as it's only a few additional docker
containers.

My motivations for doing this is that I'd like to move away from using our
own homebrew centos+Kubernetes vagrantbox and move towards using yours, and
the only difference between the two currently functionality wose is we have
an option to enable ceph (for rbd mounts).

Your is a lot tidier and less flakey than our implementation so, which is
why I'm investigating how feasible using it is.

On Wed, 19 Aug 2015 18:03 Paulo Pires <notifications@github.com> wrote:

> @PurpleBooth <https://github.com/PurpleBooth> it's still not clear to me
> what would be the gains, since this is mostly used for development
> purposes. Would it be optional? Would it be *free*, in the sense of
> configuring everything needed and not consume too much resources, for any
> user?
> I am aware of Ceph but never seen it outside of datacenters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pires/kubernetes-vagrant-coreos-cluster/issues/148#issuecomment-132696462>
> .
>
-- 
Billie Thompson
Software Developer
Purple Booth Ltd

Mob: 07813452516
Web: purplebooth.co.uk
Keybase: <http://billie.codes/1NOw29c>
LinkedIn: <http://billie.codes/1KT8gcI>
Twitter: <http://billie.codes/1SGPMCw>

**Comment by pires** [comment]
Awesome! Bring it on.

**Comment by pires** [comment]
Stalled.

**Comment by PurpleBooth** [comment]
Sorry we went a different route in the end. Forgot to update this.
