### ISSUE TITLE
setup-network-environment really necessary?

### ISSUE THREAD

**Issue by jonaz** [pires/kubernetes-vagrant-coreos-cluster#150]
Hi

Why is the setup-network-environment service needed?
The environment variables it creates does not seem to be used anywhere on the master or the nodes? 

```EnvironmentFile=/etc/network-environment``` is passed to the kubelet but i cannot find that the kubelet uses it. 

I've started my cluster without it and it works fine. 

If you agree it is not needed i can make PR to remove it.

**Comment by pires** [comment]
Create the PR and I'll review.

**Comment by jonaz** [comment]
PR #151
