### ISSUE TITLE
DNS skydns pod restarts when it is in secure/https mode. 

### ISSUE THREAD

**Issue by mattma** [pires/kubernetes-vagrant-coreos-cluster#153]
Using the file [dns-controller.yaml](https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/dns/dns-controller.yaml.tmpl) to setup the DNS, there is one variation on my setup. I uses Secure connection (https) instead of Insecure connection (http). 

At [line 42](https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/dns/dns-controller.yaml.tmpl#L42), I changed it to `- -kube_master_url=https://__MASTER_IP__:6443 `

I kicked start my cluster. One of three container (gcr.io/google_containers/skydns:2015-03-11-001) keeps restarts itself. 

So I logon one of them, found this. 

```
core@kube-node-02 ~ $ docker logs 173f0cf85c5f
2015/09/03 18:41:23 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [2]
2015/09/03 18:41:23 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2015/09/03 18:41:23 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]
```

Is it because that it cannot talk to API server since I am in the container itself? need to have a privilege true or something?

thanks.

**Comment by pires** [comment]
That log is not an error. Code 100 is an etcd error message meaning there was no key. This is expected.

**Comment by mattma** [comment]
```
 Thu, 03 Sep 2015 12:33:16 -0700	Thu, 03 Sep 2015 12:33:16 -0700	1	{kubelet 172.17.8.101}	spec.containers{skydns}			created		Created with docker id ab10b99c20d5
  Thu, 03 Sep 2015 12:33:45 -0700	Thu, 03 Sep 2015 12:33:45 -0700	1	{kubelet 172.17.8.101}	spec.containers{skydns}			killing		Killing with docker id ab10b99c20d5
  Thu, 03 Sep 2015 12:33:46 -0700	Thu, 03 Sep 2015 12:33:46 -0700	1	{kubelet 172.17.8.101}	spec.containers{skydns}			started		Started with docker id ffe58a1e9d72
  Thu, 03 Sep 2015 12:33:46 -0700	Thu, 03 Sep 2015 12:33:46 -0700	1	{kubelet 172.17.8.101}	spec.containers{skydns}			created		Created with docker id ffe58a1e9d72
  Thu, 03 Sep 2015 12:34:15 -0700	Thu, 03 Sep 2015 12:34:15 -0700	1	{kubelet 172.17.8.101}	spec.containers{skydns}			killing		Killing with docker id ffe58a1e9d72
  Thu, 03 Sep 2015 12:34:16 -0700	Thu, 03 Sep 2015 12:34:16 -0700	1	{kubelet 172.17.8.101}	spec.containers{skydns}			created		Created with docker id 67aeb6a50c85
  Thu, 03 Sep 2015 12:34:16 -0700	Thu, 03 Sep 2015 12:34:16 -0700	1	{kubelet 172.17.8.101}	spec.containers{skydns}			started		Started with docker id 67aeb6a50c85
  Thu, 03 Sep 2015 12:34:45 -0700	Thu, 03 Sep 2015 12:34:45 -0700	1	{kubelet 172.17.8.101}	spec.containers{skydns}			killing		Killing with docker id 67aeb6a50c85
  Thu, 03 Sep 2015 12:34:46 -0700	Thu, 03 Sep 2015 12:34:46 -0700	1	{kubelet 172.17.8.101}	spec.containers{skydns}			created		Created with docker id ac8651f1b24e
  Thu, 03 Sep 2015 12:34:46 -0700	Thu, 03 Sep 2015 12:34:46 -0700	1	{kubelet 172.17.8.101}	spec.containers{skydns}			started		Started with docker id ac8651f1b24e
  Thu, 03 Sep 2015 12:35:15 -0700	Thu, 03 Sep 2015 12:35:15 -0700	1	{kubelet 172.17.8.101}	spec.containers{skydns}			killing		Killing with docker id ac8651f1b24e
  Thu, 03 Sep 2015 12:16:45 -0700	Thu, 03 Sep 2015 12:35:15 -0700	38	{kubelet 172.17.8.101}	spec.containers{skydns}			unhealthy	Liveness probe failed: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
```

I read the [docs](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns) in details. I think the problem is in the secure environment, [`nslookup`](https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/dns/dns-controller.yaml.tmpl#L68) is resolved on port `8080`, it should be running on `6443`. Maybe from [Google example](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in#L84) here?

I tried this, and it did not work, maybe i have the wrong format, could you correct me?

```
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
            - -port 6443
          initialDelaySeconds: 30
          timeoutSeconds: 5
```

**Comment by pires** [comment]
Port 8080 is still available. I will check.

**Comment by mattma** [comment]
Yes, 8080 is still available but it is only for that host only. Since kubelet is trying to connect from another machine, 8080 is not available.

**Comment by pires** [comment]
Thank you for reporting.
