### ISSUE TITLE
Check for existing kubectl before downloading

### ISSUE THREAD

**Issue by chiefy** [pires/kubernetes-vagrant-coreos-cluster#154]
I installed `kubectl` via `brew`, it would be cool if the setup could check for it, and even check to make sure it's the latest version before downloading.

**Comment by pires** [comment]
I agree we can check if it's the latest version before downloading but I disagree not overwriting previously installed versions. This repository allows you to run any Kubernetes version (retro-compatibility is limited) so it would bring many issues if client and server versions didn't match.

Would you be interested in contributing a PR to do this?

**Comment by chiefy** [comment]
@pires :+1: yes, will try to get to it asap.

**Comment by pires** [comment]
@chiefy awesome!
