### ISSUE TITLE
public_address_override DEPRECATED

### ISSUE THREAD

**Issue by tdeheurles** [pires/kubernetes-vagrant-coreos-cluster#156]
hi Paulo,

Just to mention :
On master.yaml, for the api-server, `public_address_override` is now DEPRECATED.
The recommended parameter is `--bind-address`

(not already tested for me)

**Comment by pires** [comment]
@tdeheurles care to test the new flag and provide a PR? Glad to review it!

**Comment by tdeheurles** [comment]
Sure @pires , I posted as a reminder, for now I'm in trouble with configuring my kubernetes cluster (not that project one). I came back as soon as it's tested.

**Comment by pires** [comment]
Thank you.
