### ISSUE TITLE
Delete DTC code

### ISSUE THREAD

**Issue by navats** [pires/kubernetes-vagrant-coreos-cluster#159]
Hi Pires,

First, Thank you for making this java obi api, this api was really useful when making an android based obd application.

So far, I was able to make every function work on both simulator and real car except clearing the DTC code since I couldn’t find the command to do so.

Do you have any suggestion on how do I clear the fault code using this api.

Thank you in advance,

**Comment by pires** [comment]
You're on the wrong project. Please jump to https://github.com/pires/obd-java-api.
