### ISSUE TITLE
Rather than installing kubectl globally and modifng ~/.bash_profile, consider providing script that emits shell evaluable config

### ISSUE THREAD

**Issue by orospakr** [pires/kubernetes-vagrant-coreos-cluster#160]
A big part of the value of using Vagrant to host environments is achieving isolation of your project workload from the rest of your workstation.  I get very nervous when projects start asking to make changes to my global setup.

It'd be great if perhaps the user was asked to run, at their convenience, something like:

    $ eval "$(kubernetes-cluster shellinit)"

The script would emit a shell snippet to stdout that appends a path to a local copy of kubectl onto PATH, and also sets FLEETCTL_ENDPOINT and KUBERNETES_MASTER. Similar to what boot2docker, rbenv, and others do.

Cheers!

**Comment by pires** [comment]
Thanks for sharing. Personally, I dislike how `docker` does it. For someone, like me, who has a couple dozen terminal tabs open it's a major PITA to run said `eval` instruction.

Anyway, I'm open for reviewing a PR.
