### ISSUE TITLE
Minions start but don't attach to master / laggy ssh session

### ISSUE THREAD

**Issue by chiefy** [pires/kubernetes-vagrant-coreos-cluster#170]
I'm not really sure if this problem is exclusive to this project, but my google-fu failed me on finding anyone else experiencing this exactly.

What I have:
 * OSX 10.10.5
 * Vagrant 1.7.4
 * VirtualBox 5.0.2

I run `NODE_MEM=1512 CLOUD_PROVIDER=vagrant USE_KUBE_UI=true vagrant up` and everything seems to come up fine. I can ssh into master, and everything is fine. When I ssh into either of the minions however, there is a long delay (20-30s) and then there is a typing delay, usually about 10-15s. Very annoying. Load average on these minions is minimal. I can ping the master's IP, though the response times are somewhat high (500-1500ms).

Anyone have ideas on how to track down what is going on? Someone in a CoreOS issue had a similar problem a while back and it was DNS related?

```
❯ kubectl cluster-info && kubectl get nodes && kubectl get pods
Kubernetes master is running at http://172.17.8.101:8080
NAME      LABELS    STATUS
NAME               READY     STATUS    RESTARTS   AGE
kube-dns-yteiz     0/3       Pending   0          40m
kube-ui-v2-b6xg8   0/1       Pending   0          40m
```

**Comment by pires** [comment]
No nodes are provisioned/registered in the Kubernetes cluster. Pods and Services have been created in the API (`master`) and that's why you're seeing that result. Could the nodes still be downloading `kubelet`? Or having networking issues? Have you [disabled DHCP](https://github.com/pires/kubernetes-vagrant-coreos-cluster#virtualbox)?

**Comment by sdval** [comment]
I'm running into the same issue. Above `kubectl` commands return the same output. Additionally, `vagrant status` returns:
```
vagrant status
Current machine states:

master                    running (virtualbox)
node-01                   running (virtualbox)
node-02                   running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

I did find this in `journalctl` on my minions:
```
Oct 16 21:20:21 node-01 kubelet[1154]: E1016 21:20:21.088075    1154 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: Post http://kubernetes-master:8000/login: dial tcp: lookup kubernetes-master: no such host
Oct 16 21:20:23 node-01 kubelet[1154]: E1016 21:20:23.213325    1154 kubelet.go:1641] error getting node: node 172.17.8.102 not found
```
I also ran `VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnetN`. All and any help is greatly appreciated here. Thanks!

**Comment by tdeheurles** [comment]
can you ping between the different master/node plz ?

```
vagrant ssh master
ping 172.17.8.102
etc
```

**Comment by pires** [comment]
> Post http:// <http://kubernetes-master:8000/login>kubernetes-master
<http://kubernetes-master:8000/login>:8000/login
<http://kubernetes-master:8000/login>: dial tcp: lookup kubernetes-master:
no such host

Where does this hostname come from? This is not something from my repo.
Unless it's some Kubernetes bug.

**Comment by sdval** [comment]
I rebooted, removed the virtual box images, pulled from mater, and re- ```vagrant up```-ed and everything is working now. Sorry for the noise - and thanks for putting this repo out there!

**Comment by pires** [comment]
Great @sdval. Thank you.
