### ISSUE TITLE
migrating to current docker-registry?

### ISSUE THREAD

**Issue by remoe** [pires/kubernetes-vagrant-coreos-cluster#173]
This project use a deprecated docker-registry 0.9.1:

https://github.com/docker/docker-registry
https://github.com/AntonioMeireles/dockerfiles/blob/master/docker-registry/Dockerfile

Does anyone know how to migrate to this:

https://github.com/docker/distribution
docs: https://docs.docker.com/registry/deploying/
?

This should be changed?:

https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/master.yaml#L42

**Comment by pires** [comment]
Never tried the new `docker-distribution` so I have no idea how to proceed. PR welcome.

**Comment by remoe** [comment]
@pires, I'm not very familiar with it, but I've tried it:

https://github.com/pires/kubernetes-vagrant-coreos-cluster/pull/174

Thoughts?
