### ISSUE TITLE
/bin/sh: /home/core/kubectlsetup: No such file or directory

### ISSUE THREAD

**Issue by WRidder** [pires/kubernetes-vagrant-coreos-cluster#177]
At the moment I'm experiencing a weird issue using current master. Basically the steps I took are:
- Clone current master in a new folder
- Run `vagrant up` (Runs fine and I can enter the master/nodes)
- Run `vagrant destroy -f`
- Run `vagrant up`
- Error below occurs: 

```bash
==> master: Running provisioner: file...
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running triggers after up...
==> master: Sanitizing stuff...
Could not open a connection to your authentication agent.
==> master: Waiting for Kubernetes master to become ready...
==> master: Installing kubectl for the Kubernetes version we just bootstrapped...
==> master: Executing remote command "sudo -u core /bin/sh /home/core/kubectlsetup install"...
==> master: /bin/sh: /home/core/kubectlsetup: No such file or directory
==> master: Remote command execution finished.
The command "sudo -u core /bin/sh /home/core/kubectlsetup install" returned a failed exit code. The
error output is shown below:

/bin/sh: /home/core/kubectlsetup: No such file or directory
```

Cloning the current master in a new folder now results in immediately receiving the aforementioned error instead of after a first single successful run.

Platform: Win10

**Comment by pires** [comment]
Can you verify if the `temp` folder is populated?

**Comment by WRidder** [comment]
The temp directory contains a `dns-controller.yaml` and a `setup` file.

**Comment by WRidder** [comment]
Hm, this is odd. I deleted my base-boxes in `C:\Users\<USERNAME>\.vagrant.d\boxes`. Next running `vagrant up` actually works again. 

However, when running `vagrant destroy -f` and `vagrant up` subsequently; the same error pops up again.

Is the base box altered in any way? (core-alpha 884.0.0 in this case)

**Comment by pires** [comment]
Not that I'm aware of. `vagrant destroy -f` followed by `vagrant up` should repeat all steps executed in the initial (successful) run. I can't help with more debugging since I don't have any Windows machine around.

**Comment by tdeheurles** [comment]
I have the same issue starting from scratch.

![image](https://cloud.githubusercontent.com/assets/9496645/13547257/a4cc15d4-e2cb-11e5-98ea-2de43bb27bbe.png)

---

![image](https://cloud.githubusercontent.com/assets/9496645/13547265/befb39da-e2cb-11e5-802f-63eebcc28924.png)

Note that now there is a kubectl version for windows users that can be downloaded with the different binaries: [https://storage.googleapis.com/kubernetes-release/release/v1.1.4/bin/windows/amd64/kubectl.exe](https://storage.googleapis.com/kubernetes-release/release/v1.1.4/bin/windows/amd64/kubectl.exe)

**Comment by pires** [comment]
@tdeheurles care to open a PR that uses the Windows binary on the host instead of the Linux binary on the VM?

**Comment by tdeheurles** [comment]
I'll try, but not now sorry ... 

We need to remove the `windows kubectl speciality` and add a link to the windows kubectl.exe I think. It will be more consistent between environment. I'll try to do that ...

For information I'm totally not using that way anymore. For me, kubectl is included in a container now. The method works for all environment. If someone is interested, it's [here](https://github.com/tdeheurles/hive).

I definetly need to deploy a local kubernetes but I don't know which solution to use as each have it's own issues :-/ Windows is definetly not easy to manage for docker stuff ...

**Comment by AntAreS24** [comment]
Same issue here. I'm new to all this, so I'm happy to, but I'd need some guidance.

**Comment by tdeheurles** [comment]
Look to the *.sh scripts. If their line endings are CRLF, your clone is not good.
You can:
- change line ending using your editor (intellij, atom or visual code do that).

or:
- delete the repo, block git to change LF to CRLF with `git config core.autocrlf false` and clone again.
