### ISSUE TITLE
Port 8080 not exposed localy

### ISSUE THREAD

**Issue by ankitforcode** [pires/kubernetes-vagrant-coreos-cluster#180]
Seems after doing "vagrant up" port 8080 is not getting exposed externally as kubectl is unable to connect to the Kubernetes API.

error: couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused

**Comment by pires** [comment]
The Kubernetes API is exposed on your master VM IP address not localhost.
