### ISSUE TITLE
Creating Binaries again during vagrant up

### ISSUE THREAD

**Issue by rajasaur** [pires/kubernetes-vagrant-coreos-cluster#186]
Hi, 
When you re-run vagrant up (after a vagrant halt), it re-runs the systemd units thus creating multiple copies of kube-proxy, kubelet, kube-scheduler, kube-apiserver (depending on master/node). Should we be using the ConditionPathExists (or something similar) so that it doesnt re-create the entries.

Same with the kubectl binary. The setup script checks for the directory existence and execute bit conditionally and creates it only if its not there, but the binary is downloaded everytime I run vagrant up. Can we make this conditional or is there a reason behind running it every time. (EDIT: Just saw #154 was raised for this)

I can work on a PR if its acceptable. 

Thanks for building this!

**Comment by pires** [comment]
Yes, I'm eager to review your PRs :+1:

**Comment by rajasaur** [comment]
@pires : Raised a PR #187 for this. Please note that this doesnt do as extensive a test on kubectl (by checking binary versions etc as mentioned in #154) as I wanted to do that separately. This will just avoid downloading it and makes the subsequent vagrant up times much shorter since the downloads of the binary and the kubectl are avoided.

**Comment by pires** [comment]
Please, do it in a separate PR and remove the `kubectl` part of #187.

**Comment by rajasaur** [comment]
@pires : Im going to do some debugging to see if the following error is related to my change (Cant see how it could have), but Ive been unable to pull any images from the registry cache. I keep getting errors like

Handler for GET /images/gcr.io/google_samples/gb-frontend:v3/json returned error: No such image:

for each of the images that are defined in the yaml files. If I do a docker pull manually from the minions, then it works fine, but that should have been done automatically. Not sure how my change could have caused it. Im going to revert my changes and see if it goes away.

Do you have any pointer why this could happen?  It almost looks like the docker-registry is not calling the public network to get and cache it, but returning 404 all the time (Hence my pods are eternally in "ContainerCreating" state)

**Comment by pires** [comment]
`gcr.io` is not cached at all, only Docker Hub.
