### ISSUE TITLE
How to expose ports

### ISSUE THREAD

**Issue by Industrial** [pires/kubernetes-vagrant-coreos-cluster#196]
Hi!

I've ran this project and then installed your elasticsearch and elk stack projects on the kubernetes running in vagrant but I have no idea how to expose services so I can for example see Kibana from the host machine.

**Comment by pires** [comment]
You should read about [Services](http://kubernetes.io/docs/user-guide/services/) to understand how services are exposed.

Now, you should be able to access services by accessing the VM network but this is out of the scope of this project. Still, https://www.vagrantup.com/docs/networking/forwarded_ports.html.

**Comment by Industrial** [comment]
I have now read up on Services and I see that if I use the `type: NodePort` then
Kubernetes will dish out a port from 30000 to 32767 (see
[here](http://kubernetes.io/docs/user-guide/services/#type-nodeport)).

When I have everything running e.g. your elasticsearch and elk clusters then
kibana which runs on port 80 on the *Container* and a random port on the node.

The output from `kubectl get nodes` is the IP's of the vagrant VM's if I check
that with `vagrant ssh` and `ifconfig`.

When I try to access the service on the random port reported in the Kubernetes
Dashboard then I get an endless connection attempt.

I've been trying to edit the Vagrantfile to make it exposea range of ports
([here](https://gist.github.com/Industrial/d64493168e0c3ce53c7a7c798518945c/ea486602363fb34dc7ab487bdf3c7fbb91e60889#file-vagrantfile-L215)).
but that doesn't work.

Any help would be appreciated. :-)

**Comment by rookiec14** [comment]
Industrial, did you get this working?

**Comment by Industrial** [comment]
Hi yes I did. Sorry for keeping this open..

**Comment by rookiec14** [comment]
Could you explain how you did it ?.  I also tried to forward ports for the workers nodes in the vagrant file but did not work.  Thanks.
