### ISSUE TITLE
Download Kubernetes binaries via synced folders - get rid of wget

### ISSUE THREAD

**Issue by ravihansa3000** [pires/kubernetes-vagrant-coreos-cluster#197]
Master node is using wget to download K8S binaries which consumes a lot of network bandwidth and delays the startup time. Would you be willing to add offline support (not 100% though) for installing K8S via synced folders. Basically you download the binaries separately and store them in the file system, which is mounted to master node via sync_folders.yaml. In cloud-init we copy those binaries from mount location to /opt/bin instead of wget.

Have a look at [1]. I'm using this regularly and it deploys a 2 node cluster within 2 mins. This is not generic or applicable in most cases. However, if you are interested I can work on something that might be. Just wanted to check with you before I start.

[1] https://github.com/ravihansa3000/kubernetes-vagrant-coreos-cluster/commit/61513d2d00012eb5d0f309dc6afa7f9774972b68

**Comment by pires** [comment]
The idea is mostly good but one way or another, we need to make sure the existing binaries match the configured Kubernetes version. And here's the problem, not everyone is using the latest, etc.

However, there's room for improvement on the `node` side, where only the first node would actually download the files and the remaining nodes would use said files.

**Comment by ravihansa3000** [comment]
Regarding the issue of downloaded files' version, that is trivial to solve. This has already been done for kubectl installation. Have a look at [1]. I just checked and verified that all Kubernetes binaries provide "--version" option.

Of course the default behavior is going to be `wget` and sync_folders approach is just an alternative method. This would greatly help people sitting behind too slow/restricted corporate networks.

[1] https://github.com/pires/kubernetes-vagrant-coreos-cluster/commit/11b48369a0aef60b6ff9695eb519beb0dcc46ecb#diff-f30a9e55980d36e2ec8d1d5155cc0790R34

**Comment by pires** [comment]
I'm sold. Care to provide a PR?

**Comment by ravihansa3000** [comment]
Sent PR - https://github.com/pires/kubernetes-vagrant-coreos-cluster/pull/198

Please review.

**Comment by pires** [comment]
This is done. Thanks @ravihansa3000!

**Comment by ravihansa3000** [comment]
Great!

Thanks for seeing this through to the end
