### ISSUE TITLE
Error from server

### ISSUE THREAD

**Issue by nvrenuf** [pires/kubernetes-vagrant-coreos-cluster#204]
Default settings and receive:

Error from server: error when creating "/home/core/kube-system.yaml": namespaces "kube-system" already exists

Stops after creating first server

**Comment by pires** [comment]
This should only happen once after `master` is created. Please, run the following:
```
vagrant destroy -f
vagrant up
```
and report logs.

**Comment by nvrenuf** [comment]
master: Executing remote command "/opt/bin/kubectl create -f /home/core/kube-system.yaml"...
==> master: Error from server: error when creating "/home/core/kube-system.yaml": namespaces "kube-system" already exists
==> master: Remote command execution finished.
The remote command "/opt/bin/kubectl create -f /home/core/kube-system.yaml" returned a failed exit
code or an exception. The error output is shown below:

Error from server: error when creating "/home/core/kube-system.yaml": namespaces "kube-system" already exists

**Comment by pires** [comment]
Can you share the full logs of the commands I asked you to run?

**Comment by nvrenuf** [comment]
Where are the logs located?

**Comment by pires** [comment]
Where did you get the logs you shared above?

**Comment by nvrenuf** [comment]
Copied from the screen

**Comment by pires** [comment]
There you go.

**Comment by nvrenuf** [comment]
C:\Users\lee\Documents\Vagrant\kubernetes-vagrant-coreos-cluster-master>vagrant up --provider vmware_workstation
Bringing machine 'master' up with 'vmware_workstation' provider...
Bringing machine 'node-01' up with 'vmware_workstation' provider...
Bringing machine 'node-02' up with 'vmware_workstation' provider...
==> master: Running triggers before up...
==> master: 2016-07-21 17:22:59 -0600: setting up Kubernetes master...
==> master: Setting Kubernetes version 1.3.2
==> master: Downloading Kubernetes binaries if version mismatch or binaries not present..
==> master: Checking for ./binaries/kube-apiserver with version v1.3.2..
==> master: Versions match, checking if binary exists...
==> master: Checking for ./binaries/kube-controller-manager with version v1.3.2..
==> master: Versions match, checking if binary exists...
==> master: Checking for ./binaries/kube-scheduler with version v1.3.2..
==> master: Versions match, checking if binary exists...
==> master: Checking for ./binaries/kube-proxy with version v1.3.2..
==> master: Versions match, checking if binary exists...
==> master: Checking for ./binaries/kubelet with version v1.3.2..
==> master: Versions match, checking if binary exists...
==> master: Cloning VMware VM: 'coreos-alpha'. This can take some time...
==> master: Checking if box 'coreos-alpha' is up to date...
==> master: Verifying vmnet devices are healthy...
==> master: Preparing network adapters...
==> master: Fixed port collision for 22 => 2222. Now on port 2201.
==> master: Starting the VMware VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 192.168.163.174:22
    master: SSH username: core
    master: SSH auth method: private key
==> master: Machine booted and ready!
==> master: Forwarding ports...
    master: -- 22 => 2201
==> master: Setting hostname...
==> master: Configuring network adapters within the VM...
==> master: Exporting NFS shared folders...
==> master: Preparing to edit nfs mounting file.
[NFS] Status: running
==> master: Mounting NFS shared folders...
==> master: Setting time zone...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Copying host:./binaries/kube-apiserver to vm:/opt/bin/kube-apiserver..
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Copying host:./binaries/kube-controller-manager to vm:/opt/bin/kube-controller-manager..
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Copying host:./binaries/kube-scheduler to vm:/opt/bin/kube-scheduler..
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running triggers after up...
==> master: Waiting for Kubernetes master to become ready...
==> master: 2016-07-21 17:24:02 -0600: successfully deployed master
==> master: Installing kubectl for the Kubernetes version we just bootstrapped...
==> master: Executing remote command "sudo -u core /bin/sh /home/core/kubectlsetup install"...
==> master: Downloading and installing linux version of 'kubectl' v1.3.2 into /opt/bin. This may take a couple minutes, depending on your internet speed..
==> master: Configuring environment..
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config set-cluster local --server=http://172.17.20.101:8080 --insecure-skip-tls-verify=true"...
==> master: cluster "local" set.
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config set-context local --cluster=local --namespace=default"...
==> master: context "local" set.
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config use-context local"...
==> master: switched to context "local".
==> master: Remote command execution finished.
==> master: Configuring Kubernetes DNS...
==> master: Executing remote command "/opt/bin/kubectl create -f /home/core/kube-system.yaml"...
==> master: Error from server: error when creating "/home/core/kube-system.yaml": namespaces "kube-system" already exists
==> master: Remote command execution finished.
The remote command "/opt/bin/kubectl create -f /home/core/kube-system.yaml" returned a failed exit
code or an exception. The error output is shown below:

Error from server: error when creating "/home/core/kube-system.yaml": namespaces "kube-system" already exists

**Comment by pires** [comment]
Thank you. Will check in tomorrow.
