### ISSUE TITLE
Enable deployments in Kubernetes Cluster

### ISSUE THREAD

**Issue by SabraO** [pires/kubernetes-vagrant-coreos-cluster#205]
When I query the cluster using "kubectl get deployments --namespace=default" I get the response "Unable to list "deployments": the server could not find the requested resource'". Is there any way to enable deployments in the cluster?

**Comment by pires** [comment]
Works here with a fresh clone!

```
$ kubectl get nodes
NAME           STATUS    AGE
172.17.8.102   Ready     1m
172.17.8.103   Ready     1m

$ kubectl get namespaces
NAME          STATUS    AGE
default       Active    4m
kube-system   Active    4m

$ kubectl get deployments --namespace=default
$ kubectl get svc,rc --namespace=default
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   10.100.0.1   <none>        443/TCP   4m
```

**Comment by SabraO** [comment]
The old clone I took about a week ago still works without any issue, but the fresh clone fails at starting the nodes. 

The gist for startup log can be seen at https://gist.github.com/SabraO/f4a5b13646733d2932959a139378ddf1

The Virtualbox console shows the error message "IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready".

Any ideas why the new clone is failing to start?

**Comment by pires** [comment]
If you want to enable specific APIs, you'll have to look into Kubernetes docs. Also, not sure which version of `kubectl` you're using, but I'd recommend using the same version as the server, e.g. `1.1.7.`. Also, `Deployments` for version `1.1.x` are not compatible with `1.2.x` or newer due to an API-breaking change.

**Comment by SabraO** [comment]
The kubectl version is also same as the cluster.

Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}

And after some research enabled deployments by making the following change in https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/master.yaml#L113

 --runtime_config=api/v1,extensions/v1beta1/deployments=true

Thanks for the support.
