### ISSUE TITLE
service resolving issue in k8s1.3.2 setup

### ISSUE THREAD

**Issue by amalkasubasinghe** [pires/kubernetes-vagrant-coreos-cluster#210]
Hi,

I used your script to setup k8s 1.3.2
and then I deployed heapster https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb
but I see log of heapster, influxdb and grafana errors saying it can't find other services. I logged in to the heapster node and try to curl/ping monitoring-grafana -> it says unknown host

When I deploy the heapster in default namespace, no errros in logs and heapster can find out monitoring-grafana, monitoring-influxdb correctly.

I think this is a issue in this setup. Can you help me to figure it out?

**Comment by pires** [comment]
Probably your DNS is not running.

**Comment by pires** [comment]
Run `kubectl get pods --namespace kube-system` and paste the result here.
