### ISSUE TITLE
Adopt Docker overlay2 fs

### ISSUE THREAD

**Issue by analytik** [pires/kubernetes-vagrant-coreos-cluster#212]
Hi,

This is a lazy man's pull request. I'm playing with the latest CoreOS alpha, and I'm in love with overlay2 storage driver. It's much faster, and saves 30~40% of disk space.

In Kubernetes 1.4, it seems that IPs are not allowed as node names anymore, so that needs a few changes - I'm sure there's a better way than mine, but maybe posting this will save some time for some people.

To enable overlay2, you need to have Docker 1.12 and add something to DOCKER_OPTIONS like `--storage-driver=overlay2`. That should do the trick for new machines; don't forget if you'd want to upgrade an existing machines, all your "overlay1" images will go **poof**, but also you have to manually delete the whole overlay folder to save disk space.

I currently use 1-VM setup, where master and node are on the same machine, so I added this to `write-files` in `master.yaml`:

```
  - path: /etc/hosts
    content: |
      127.0.0.1       localhost
      ::1             localhost
      __MASTER_IP__  master
```

And for kubelet setup in `node.yaml`, you'll need to remove the line `--hostname_override=$public_ipv4 \`. This has possibly other consequences, but again, for my master-node setup it works.

That's all I know for now.

**Comment by pires** [comment]
Thanks @analytik this seems pretty valuable information.

Now, enabling `overlay2` implicitly would break stuff for people opting to use older versions of CoreOS (stable or beta channels where Docker 1.12 has not yet hit).

As for hostnames, I'll have to look into Kubernetes docs and see exactly what's going on because there's no DNS outside of the Kubernetes cluster itself.

**Comment by analytik** [comment]
I think the related Kubernetes ticket is https://github.com/kubernetes/kubernetes/pull/30956

**Comment by pires** [comment]
@analytik that issue is only related to federation.

**Comment by analytik** [comment]
@pires ah, my bad

I saw the PR that affected it, but it turns out that was specific probably only to 1.4.0-beta.0 anyway, since 4 days ago that logic got reverted, and IP addresses are legal as host names again - https://github.com/kubernetes/kubernetes/pull/32052/commits/1c9ee74987a5e064638a4301c47086f6962caff0

**Comment by pires** [comment]
So it seems `overlay2` Kernel support is there for all CoreOS channels but can't move there until Docker 1.12+ is adopted as well (_alpha_ already has it).

**Comment by pires** [comment]
_beta_ bundles Docker 1.12+ too.

**Comment by pires** [comment]
`stable` has it too, now.
