### ISSUE TITLE
 Vagrant up fails at "namespaces "kube-system" already exists"

### ISSUE THREAD

**Issue by linearregression** [pires/kubernetes-vagrant-coreos-cluster#219]
Platform Windows.
Downloaded the latest and  I just did vagrant up. 
When Configuring Kubernetes DNS...
==> master: Executing remote command "/opt/bin/kubectl create -f /home/core/kube-system.yaml"...
==> master: Error from server: error when creating **"/home/core/kube-system.yaml": namespaces "kube-system" already exists**

The complete log.

==> master: Mounting NFS shared folders...
==> master: Setting time zone...
==> master: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> master: flag to force provisioning. Provisioners marked to run always will still run.
==> master: Running triggers after up...
==> master: Waiting for Kubernetes master to become ready...
==> master: 2016-11-08 21:40:18 -0800: successfully deployed master
==> master: Installing kubectl for the Kubernetes version we just bootstrapped...
==> master: Executing remote command "sudo -u core /bin/sh /home/core/kubectlsetup install"...
==> master:
==> master: kubectl already installed in version '1.3.0'. Skipping install.
==> master: Configuring environment..
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config set-cluster local --server=http://172.17.8.101:8080 --insecure-skip-tls-verify=true"...
==> master:
==> master: cluster "local" set.
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config set-context local --cluster=local --namespace=default"...
==> master:
==> master: context "local" set.
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config use-context local"...
==> master:
==> master: switched to context "local".
==> master: Remote command execution finished.
==> master: Configuring Kubernetes DNS...
==> master: Executing remote command "/opt/bin/kubectl create -f /home/core/kube-system.yaml"...
==> master:
==> master: Error from server: error when creating "/home/core/kube-system.yaml": namespaces "kube-system" already exists
==> master: Remote command execution finished.
The remote command "/opt/bin/kubectl create -f /home/core/kube-system.yaml" returned a failed exit
code or an exception. The error output is shown below:

Error from server: error when creating "/home/core/kube-system.yaml": namespaces "kube-system" already exists

C:\Users\developer\Downloads\kubernetes-vagrant-coreos-cluster-reduceresource>c

**Comment by pires** [comment]
> ==> master: Machine already provisioned. Run vagrant provision or use the --provision
==> master: flag to force provisioning. Provisioners marked to run always will still run.

This means you have previous state stored. Try: ```
vagrant destroy -f
vagrant up
```

**Comment by linearregression** [comment]
I have done that and the same error. See log beflow:

C:\Users\developer\Downloads\kubernetes-vagrant-coreos-cluster-reduceresource**>vagrant destroy -f**
==> node-02: VM not created. Moving on...
==> node-01: VM not created. Moving on...
==> master: Destroying VM and associated drives...
==> master: Pruning invalid NFS exports.
==> master: Running triggers after destroy...

C:\Users\developer\Downloads\kubernetes-vagrant-coreos-cluster-reduceresource>vagrant up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'node-01' up with 'virtualbox' provider...
Bringing machine 'node-02' up with 'virtualbox' provider...
==> master: Running triggers before up...
==> master: 2016-11-09 09:40:31 -0800: setting up Kubernetes master...
==> master: Setting Kubernetes version 1.3.0
==> master: Downloading Kubernetes binaries if version mismatch or binaries not present..
==> master: Checking for ./binaries/kube-apiserver with version v1.3.0..
==> master: Versions match, checking if binary exists...
==> master: Checking for ./binaries/kube-controller-manager with version v1.3.0..
==> master: Versions match, checking if binary exists...
==> master: Checking for ./binaries/kube-scheduler with version v1.3.0..
==> master: Versions match, checking if binary exists...
==> master: Checking for ./binaries/kube-proxy with version v1.3.0..
==> master: Versions match, checking if binary exists...
==> master: Checking for ./binaries/kubelet with version v1.3.0..
==> master: Versions match, checking if binary exists...
==> master: Importing base box 'coreos-alpha'...
==> master: Matching MAC address for NAT networking...
==> master: Checking if box 'coreos-alpha' is up to date...
==> master: Setting the name of the VM: kubernetes-vagrant-coreos-cluster-reduceresource_master_1478713245540_38779
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 (guest) => 2222 (host) (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2222
    master: SSH username: core
    master: SSH auth method: private key
==> master: Machine booted and ready!
==> master: Setting hostname...
==> master: Configuring and enabling network interfaces...
==> master: Exporting NFS shared folders...
==> master: Preparing to edit nfs mounting file.
[NFS] Status: halted
[NFS] Start: started
==> master: Mounting NFS shared folders...
==> master: Setting time zone...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Copying host:./binaries/kube-apiserver to vm:/opt/bin/kube-apiserver..
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Copying host:./binaries/kube-controller-manager to vm:/opt/bin/kube-controller-manager..
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Copying host:./binaries/kube-scheduler to vm:/opt/bin/kube-scheduler..
==> master: Running provisioner: file...
==> master: Running provisioner: file...
==> master: Running provisioner: shell...
    master: Running: inline script
==> master: Running triggers after up...
==> master: Waiting for Kubernetes master to become ready...
==> master: 2016-11-09 09:42:14 -0800: successfully deployed master
==> master: Installing kubectl for the Kubernetes version we just bootstrapped...
==> master: Executing remote command "sudo -u core /bin/sh /home/core/kubectlsetup install"...
==> master:
==> master: Downloading and installing linux version of 'kubectl' v1.3.0 into /opt/bin. This may take a couple minutes, depending on your internet speed..
==> master: Configuring environment..
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config set-cluster local --server=http://172.17.8.101:8080 --insecure-skip-tls-verify=true"...
==> master:
==> master: cluster "local" set.
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config set-context local --cluster=local --namespace=default"...
==> master:
==> master: context "local" set.
==> master: Remote command execution finished.
==> master: Executing remote command "/opt/bin/kubectl config use-context local"...
==> master:
==> master: switched to context "local".
==> master: Remote command execution finished.
==> master: Configuring Kubernetes DNS...
==> master: Executing remote command "/opt/bin/kubectl create -f /home/core/kube-system.yaml"...
==> master:
==> master: Error from server: error when creating "/home/core/kube-system.yaml": namespaces "kube-system" already exists
==> master: Remote command execution finished.
The remote command "/opt/bin/kubectl create -f /home/core/kube-system.yaml" returned a failed exit
code or an exception. The error output is shown below:

**Error from server: error when creating "/home/core/kube-system.yaml": namespaces "kube-system" already exists

C:\Users\developer\Downloads\kubernetes-vagrant-coreos-cluster-reduceresource>**

**Comment by pires** [comment]
You have a very old version, 1.3.0. Can you pull latest?

**Comment by linearregression** [comment]
So if I have local build of kubernetes, how can I use this to use my local build of k8s?

**Comment by linearregression** [comment]
platest pull from master works

**Comment by pires** [comment]
Awesome!
