### ISSUE TITLE
/tmp/openssl.cnf

### ISSUE THREAD

**Issue by jmwenda** [pires/kubernetes-vagrant-coreos-cluster#223]
I am running this on an ubuntu box and seem the /tmp/openssl.conf fails when handling the keys. Is there something i am doing wrong? should i use the default openssl /usr/local/lib/openssl.cnf? If not what should the /tmp/openssl.conf be having?

**Comment by pires** [comment]
The scripts and files are detailed [here](https://github.com/pires/kubernetes-vagrant-coreos-cluster/tree/master/tls).

I'm not sure exactly what your failure is.
