### ISSUE TITLE
Error on master.yaml?

### ISSUE THREAD

**Issue by remoe** [pires/kubernetes-vagrant-coreos-cluster#230]
I'm not sure, but why this has a '-' ?

https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/master.yaml#L124

UPDATE:

It fails when one enable this. But this is needed for a restart?

**Comment by pires** [comment]
In `system`, prepending a command with `-` means it can error and not break the execution. In this case, if a container named _kubelet_ doesnt exist, Docker will return an error code !=0 but the unit execution continues. Without the `-`, if the container doesn't exist, the unit execution is cancelled.
