### ISSUE TITLE
connection time out for every service

### ISSUE THREAD

**Issue by w9n** [pires/kubernetes-vagrant-coreos-cluster#232]
hi,
i run a fork with libvirt (dont think it matters, maybe certs? #229 ). I tried different services but all of them time out on the docker ip.

`curl http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/` -> 
`Error: 'dial tcp 10.244.89.2:9090: getsockopt: connection timed out'
Trying to reach: 'http://10.244.89.2:9090/'`
dashboard runs on node 1
`curl 10.244.89.2:9090` works from node 1.
`kube-system   svc/kubernetes-dashboard   10.100.70.70   <none>        80/TCP          8m
`
`curl 10.100.70.70` works from node 1 but not from master or node 2. 

flanneld, etcd logs look good. Do you have an idea whats going wrong here?

**Comment by pires** [comment]
Check notes for the provider you use. For instance, if using Virtualbox https://github.com/pires/kubernetes-vagrant-coreos-cluster#virtualbox.

**Comment by w9n** [comment]
I use [libvirt-vagrant](https://github.com/vagrant-libvirt/vagrant-libvirt) in my [fork](https://github.com/w9n/kubernetes-vagrant-coreos-cluster/tree/libvirt) (dont know if you want to support it), the box works with the offical kubernetes vagrant repo. I also can ping between the nodes but really dont know what part is failing here

**Comment by pires** [comment]
I don't know about libvirt-vagrant and I'm not thinking about moving as the current setup works just fine.

Now, one node works, the two others don't. So it's something with your set-up.

**Comment by w9n** [comment]
besides better performance and compatibility with kvm as vt-x hypervisor for other vms, the vagrant plugin enables parallel provisioning for each node.

i switched to vxlan and it easily works, just to let you know.
