### ISSUE TITLE
Why not using kubelet-wrapper?

### ISSUE THREAD

**Issue by remoe** [pires/kubernetes-vagrant-coreos-cluster#235]
I'm interested about the reason of not using kubelet-wrapper here:

https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/master.yaml#L125

?

because of using gcr.io and docker?

**Comment by pires** [comment]
This repo was using kubelet-wrapper before, which relies on rkt. I moved to Docker so I could have more control.
