### ISSUE TITLE
DNS_UPSTREAM_SERVERS not used in current kube-dns ?

### ISSUE THREAD

**Issue by remoe** [pires/kubernetes-vagrant-coreos-cluster#237]
This is not used anymore:
https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/Vagrantfile#L111

Don't find any entry in it:

https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/27f3e4e294296e1ceac67135a02fe177c7d8ef7c/plugins/dns/dns-controller.yaml.tmpl

Does anyone know the details, why is this not needed?

**Comment by pires** [comment]
I think upstream servers can be defined but no one was using them, so while updating the descriptors I forgot to remove the optional parameter. I will remove it soon.
