### ISSUE TITLE
how to get kubectl working on mac

### ISSUE THREAD

**Issue by sjeeva** [pires/kubernetes-vagrant-coreos-cluster#239]
I was able to successfully bring up the master and two nodes on mac system with virtualbox.. however kubectl is not available inside the master...
I ssh-ed into the master using below command
vagrant ssh master

How to configure external kubectl (from the mac)

**Comment by pires** [comment]
@sjeeva `kubectl` is installed and configured in the host, so on your Mac. In the same terminal you ran `vagrant up`, just run `kubectl get nodes`.

**Comment by sjeeva** [comment]
kubernetes-vagrant-coreos-cluster$ kubectl config use-context default-cluster
error: no context exists with the name: "default-cluster".
kubernetes-vagrant-coreos-cluster$ kubectl get nodes
The connection to the server 172.17.8.101 was refused - did you specify the right host or port?
kubernetes-vagrant-coreos-cluster$

**Comment by pires** [comment]
```
$ kubectl config use-context default-cluster
error: no context exists with the name: "default-cluster".
```

Why did you run this manually? `vagrant up` takes care of this for you.
