### ISSUE TITLE
Having issues connecting to k8s cluster.. only destroy and up sloves the problem

### ISSUE THREAD

**Issue by sjeeva** [pires/kubernetes-vagrant-coreos-cluster#240]
==> node-02: Running triggers after up...
==> node-02: Waiting for Kubernetes minion [node-02] to become ready...
==> node-02: 2017-03-04 10:00:11 +0530: successfully deployed node-02
kubernetes-vagrant-coreos-cluster$ kubectl get nodes
The connection to the server 172.17.8.101 was refused - did you specify the right host or port?
kubernetes-vagrant-coreos-cluster$ vagrant status
Current machine states:

master                    running (virtualbox)
node-01                   running (virtualbox)
node-02                   running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

**Comment by pires** [comment]
Have you disabled DHCP as instructed in the documentation?

**Comment by sjeeva** [comment]
VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0?
Would this impact by VMs?

**Comment by sjeeva** [comment]
things got worst after I removed the dhcpserver .. now destroy / up is also not working 

==> master: Installing kubectl for the Kubernetes version we just bootstrapped...
The connection to the server 172.17.8.101 was refused - did you specify the right host or port?
kubectl already installed in version '1.5.3'. Skipping install.
Configuring environment..
Cluster "default-cluster" set.
User "default-admin" set.
Context "local" set.
Switched to context "local".
==> master: Configuring Kubernetes DNS...
The connection to the server 172.17.8.101 was refused - did you specify the right host or port?
The connection to the server 172.17.8.101 was refused - did you specify the right host or port?

**Comment by pires** [comment]
IPs are set manually, so I'm not sure what's going on with your setup.

**Comment by pires** [comment]
And it doesn't seem to get worst as before you already had the same problem:
```
The connection to the server 172.17.8.101 was refused - did you specify the right host or port?
```

**Comment by sjeeva** [comment]
do you need any logs to help me resolve this issue?

**Comment by sjeeva** [comment]
BTW., previously destroy and up solved this issue...

**Comment by pires** [comment]
👍

**Comment by thatsk** [comment]
Actually its with Kubernetes if we disable dhcp of virtualbox it can affect to other projects so is there any way for which kubernetes cluster and other projects cluster will workk???

**Comment by thatsk** [comment]
Please open this issues

**Comment by thatsk** [comment]
This is so irritating for us to disable dhcp server of Virutalbox & destroy the cluster and up takes to much time so what we have done development is gone.....

**Comment by pires** [comment]
@thatsk if you find a solution, do open a PR. Glad to review solutions rather than commenting rants.
