### ISSUE TITLE
Surviving VM restarts

### ISSUE THREAD

**Issue by soickm** [pires/kubernetes-vagrant-coreos-cluster#243]
Great piece of work Mr Pires. I cloned and have used it quite a bit on my dev environments.

One small issue I noticed is that the environment doesn't seem to survive VM restarts. 

For example, if I stop either VM (master, node-1, node-2), the only way to re-stand the environment is by re-creating the VMs. 

Is this an issue that you can address?

Thanks,

Pedro

**Comment by pires** [comment]
Hey Pedro, unfortunately it's not. Open to review, PRs though.

**Comment by soickm** [comment]
Obrigado Paulo.
