### ISSUE TITLE
Adding kompose to primary

### ISSUE THREAD

**Issue by soickm** [pires/kubernetes-vagrant-coreos-cluster#248]
Mr Pires,

Where would you suggest I make a change to add another component to the master - such as kompose?

My limited understanding of vagrant is that I can deploy components to a VM via external scripting, but it doesnt look like this is what you are doing and I wanted to stay true to initial design.

Thanks,

Pedro

**Comment by pires** [comment]
What is kompose? Looking at https://github.com/kubernetes-incubator/kompose it seems to be a developer CLI tool you would use on your machine, not on any Kubernetes node, much less the master node. 😕
