### ISSUE TITLE
password for user core after "vagrant up" command

### ISSUE THREAD

**Issue by kamal2222ahmed** [pires/kubernetes-vagrant-coreos-cluster#252]
After i run the vagrant up @ kubernetes-vagrant-coreos-cluster level , i am prompted for a password, could not find what the password should be:

Here is a stdout:

$ vagrant up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'node-01' up with 'virtualbox' provider...
Bringing machine 'node-02' up with 'virtualbox' provider...
==> master: Running triggers before up...
==> master: 2017-07-04 10:01:15 -0400: setting up Kubernetes master...
==> master: Setting Kubernetes version 1.6.6
==> master: Checking if box 'coreos-alpha' is up to date...
==> master: Clearing any previously set forwarded ports...
==> master: Fixed port collision for 22 => 2222. Now on port 2200.
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 (guest) => 2200 (host) (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2200
    master: SSH username: core
    master: SSH auth method: private key
==> master: Machine booted and ready!
==> master: Setting hostname...
==> master: Configuring and enabling network interfaces...
==> master: Exporting NFS shared folders...
==> master: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:

**Comment by pires** [comment]
Your user's password, if it has sudo access.
