### ISSUE TITLE
Connection refused to master

### ISSUE THREAD

**Issue by taahir-hassem** [pires/kubernetes-vagrant-coreos-cluster#258]
When running `vagrant up`, the connection to the master shows connection refused errors.  kubectl also shows connection refused errors.

LOG
==> master: Waiting for Kubernetes master to become ready...
==> master: 2017-08-10 22:37:01 +0200: failed to deploy master within timeout count of 50
==> master: Installing kubectl for the Kubernetes version we just bootstrapped...
Unable to connect to the server: Connection refused
kubectl already installed in version '1.7.3'. Skipping install.
Configuring environment..
Cluster "default-cluster" set.
User "default-admin" set.
Context "local" modified.
Switched to context "local".
==> master: Configuring Kubernetes DNS...
Unable to connect to the server: Connection refused
Unable to connect to the server: Connection refused
Unable to connect to the server: Connection refused
==> master: Configuring Kubernetes dashboard...
Unable to connect to the server: Connection refused
Unable to connect to the server: Connection refused
==> master: Kubernetes dashboard will be available at http://172.17.8.101:8080/ui

All nodes show as successfully deployed.  I am also unable to reach the UI on the given URL.

**Comment by taahir-hassem** [comment]
OS : Linux Mint 18.2

When logging onto the master, I can see hyperkube running:

`core@master ~ $ docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
31905d3a8ffc        gcr.io/google_containers/pause-amd64:3.0          "/pause"                 29 minutes ago      Up 29 minutes                           k8s_POD_kube-controller-manager-172.17.8.101_kube-system_af615824e1e5c932184d4d4d451817bb_0
4dd2efbbdb6d        gcr.io/google_containers/pause-amd64:3.0          "/pause"                 29 minutes ago      Up 29 minutes                           k8s_POD_kube-proxy-172.17.8.101_kube-system_bcca324ea2a97ecd521df4481b44d52c_0
ee31ab0609a3        gcr.io/google_containers/pause-amd64:3.0          "/pause"                 29 minutes ago      Up 29 minutes                           k8s_POD_kube-apiserver-172.17.8.101_kube-system_77d839007bcba86bb6bcfc18b5763f02_0
144a05861a84        gcr.io/google_containers/pause-amd64:3.0          "/pause"                 29 minutes ago      Up 29 minutes                           k8s_POD_kube-scheduler-172.17.8.101_kube-system_0e6caf5ddad3fd32654356478f23d541_0
72600f4354b8        gcr.io/google_containers/hyperkube-amd64:v1.7.3   "/hyperkube kubele..."   29 minutes ago      Up 29 minutes                           kubelet
`

**Comment by pires** [comment]
The apiserver container isn't running. You need to check the logs of the failed container.

**Comment by taahir-hassem** [comment]
So I deleted the cluster using vagrant destroy and retries to get the cluster up and running.  Was not presented with the following error:

==> master: Running triggers before up...
==> master: 2017-08-11 17:12:23 +0200: setting up Kubernetes master...
==> master: Setting Kubernetes version 1.7.3
==> master: Box 'coreos-alpha' could not be found. Attempting to find and install...
    master: Box Provider: virtualbox
    master: Box Version: = 1492.3.0
==> master: Loading metadata for box 'http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json'
    master: URL: http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
==> master: Adding box 'coreos-alpha' (v1492.3.0) for provider: virtualbox
    master: Downloading: http://builds.release.core-os.net/alpha/amd64-usr/1492.3.0/coreos_production_vagrant.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 403 Forbidden

Tried cloning the repo again and starting from scratch but still getting the same

**Comment by taahir-hassem** [comment]
Started from scratch again and it worked.  Thanks.
