### ISSUE TITLE
Dashboard 1.7 doesn't work

### ISSUE THREAD

**Issue by munai-das** [pires/kubernetes-vagrant-coreos-cluster#266]
Here is the issue I get. 

> 
> ➜  kubernetes-vagrant-coreos-cluster git:(master) kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
> secret "kubernetes-dashboard-certs" created
> serviceaccount "kubernetes-dashboard" created
> rolebinding "kubernetes-dashboard-minimal" created
> deployment "kubernetes-dashboard" created
> service "kubernetes-dashboard" created
> Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml": roles.rbac.authorization.k8s.io "kubernetes-dashboard-minimal" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["secrets"], ResourceNames:["kubernetes-dashboard-key-holder"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["secrets"], ResourceNames:["kubernetes-dashboard-certs"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["secrets"], ResourceNames:["kubernetes-dashboard-key-holder"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["secrets"], ResourceNames:["kubernetes-dashboard-certs"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["secrets"], ResourceNames:["kubernetes-dashboard-key-holder"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["secrets"], ResourceNames:["kubernetes-dashboard-certs"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["services"], ResourceNames:["heapster"], APIGroups:[""], Verbs:["proxy"]}] user=&{kube-admin  [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
> 

Git Head of kubernetes-vagrant-coreos-cluster
```
commit 815c5e9bb66e0c27309f117beffbee195fdace25 (HEAD -> master, origin/master, origin/HEAD)
Author: Uday Kiran <udaykiran.y@gmail.com>
Date:   Sun Sep 10 15:45:33 2017 +0530
```

**Comment by pires** [comment]
I haven't tested Dashboard 1.7. But if you run `USE_KUBE_UI=true vagrant up` the previous version of the dashboard will come up.

**Comment by KptnKMan** [comment]
FYI check https://github.com/kubernetes/dashboard/issues/2415
