### ISSUE TITLE
Dashboard error in K8s 1.8 / 1.9

### ISSUE THREAD

**Issue by dwickern** [pires/kubernetes-vagrant-coreos-cluster#274]
When navigating to `/ui` there is an error:
http://172.17.8.101:8080/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://10.244.39.2:9090/'
```

It works after removing the `https:`
http://172.17.8.101:8080/api/v1/namespaces/kube-system/services/kubernetes-dashboard:/proxy/

This started happening in kubernetes 1.8. Upgrading to the latest dashboard version doesn't fix it.

**Comment by pires** [comment]
I don't know why the api proxy forces you to use HTTPS. Will have to research but I have no ETA for this.

**Comment by mrichman** [comment]
Same issue with me. Same error on http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default but it works with 172.17.8.101.

**Comment by pires** [comment]
@mrichman the problem is that Kubernetes is now enforcing HTTPS. If you pay attention to the URL `kubectl proxy` renders, you'll see `https://` in there.
