### ISSUE TITLE
Error fresh install creating temp/coredns-deploymeny.yaml

### ISSUE THREAD

**Issue by dyson** [pires/kubernetes-vagrant-coreos-cluster#275]
On a fresh install I get the following error:
```
service "coredns" created
Error from server (Forbidden): error when creating "temp/coredns-deployment.yaml": clusterroles.rbac.authorization.k8s.io "system:coredns" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["watch"]}] user=&{kube-admin  [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
```
caused by https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/3036fe1a9551473fff988a1aa7998bc637134e0a/Vagrantfile#L336

Seems there is missing privileges?

**Comment by pires** [comment]
You enabled RBAC, didn't you?

**Comment by dyson** [comment]
Oh right. I mistakenly read it was the default but it clearly says it isn't sorry.

So in that case the default of ABAC authorization mode clashes with the default of CoreDNS for DNS. Should one of them be changed so out of the box a vagrant up works with no env vars?

**Comment by pires** [comment]
Default is `AlwaysAllow` and that just works. If `RBAC` is enabled, the CoreDNS descriptors are ready and you just need to make sure your kubeconfig has credentials for a user that has super-admin permissions.

e.g. ```
$ kubectl create clusterrolebinding \
  <cluster-role-binding-name> \
  --clusterrole=cluster-admin \
  --user=<USERNAME>
```

**Comment by dyson** [comment]
Ah right great, gotcha!

Thanks!
