### ISSUE TITLE
having issues with coredns

### ISSUE THREAD

**Issue by samjoandco** [pires/kubernetes-vagrant-coreos-cluster#276]
This is more of a kubernetes issues , i was wondering if someone could help me here.

the coredns keeps crashing intermittently and once it crashes there is no way to remove it. just need to destroy the cluster and create a new one.
I even tried deleting the node however the coredns pod keeps coming back in pending status and when i try to delete it it reports the pod cannot be found.

**Comment by samjoandco** [comment]
Changing the coredns image to 1.0.2 in plugins\dns\coredns\coredns.yaml.sed fixed the crashing issue for me.
----
        image: coredns/coredns:1.0.2
----

**Comment by pires** [comment]
Thank you for reporting 👍
