### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication

### ISSUE THREAD

**Issue by vikasgubbi** [pires/kubernetes-vagrant-coreos-cluster#277]
Getting below mentioned error message in centos 7 bare metal box.

[root@kubernetes kubernetes-vagrant-coreos-cluster]# vagrant up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'node-01' up with 'virtualbox' provider...
Bringing machine 'node-02' up with 'virtualbox' provider...
==> master: Running triggers before up...
==> master: 2018-01-20 15:15:47 +0530: setting up Kubernetes master...
==> master: Setting Kubernetes version 1.9.1
==> master: Checking if box 'coreos-alpha' is up to date...
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

**Comment by pires** [comment]
Seems an issue with your Virtualbox installation or vagrant. A google search should help. I found https://github.com/hashicorp/vagrant/issues/2251 and there are quite a few things you can try. Good luck!
