### ISSUE TITLE
vagrant ssh

### ISSUE THREAD

**Issue by albertocsm** [pires/kubernetes-vagrant-coreos-cluster#28]
Unable to ssh into any node

eg.:
``` bash
$ vagrant ssh <any-node-name>
...
Permission denied (publickey,password,keyboard-interactive).
```

Vagrant key can be added to ssh-agent to fix this 
```bash
$ ssh-add ~/.vagrant.d/insecure_private_key
```

See [CoreOS blog](https://coreos.com/blog/coreos-clustering-with-vagrant/) for context

**Comment by pires** [comment]
This is related to the key not being available to your ```ssh-agent```.

**Comment by AntonioMeireles** [comment]
@albertocsm can you check please if just placing 
**config.ssh.forward_agent = true** after **config.ssh.insert_key = false** in the Vagrantfile solves your issue ?
