### ISSUE TITLE
Could not resolve host: mirrors.163.com; Unknown error

### ISSUE THREAD

**Issue by bochuxt** [pires/kubernetes-vagrant-coreos-cluster#294]
node2: http://mirrors.163.com/centos/7/os/x86_64/Packages/audit-libs-python-2.7.6-3.el7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node2: Trying other mirror.
    node2: http://mirrors.163.com/centos/7/extras/x86_64/Packages/container-storage-setup-0.8.0-3.git1d27ecf.el7.noarch.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node2: Trying other mirror.
    node2: http://mirrors.163.com/centos/7/extras/x86_64/Packages/container-selinux-2.42-1.gitad8f0f7.el7.noarch.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node2: Trying other mirror.
    node2: http://mirrors.163.com/centos/7/os/x86_64/Packages/checkpolicy-2.5-4.el7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node2: Trying other mirror.
    node2: http://mirrors.163.com/centos/7/extras/x86_64/Packages/docker-1.13.1-53.git774336d.el7.centos.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node2: Trying other mirror.
    node2: http://mirrors.163.com/centos/7/extras/x86_64/Packages/docker-client-1.13.1-53.git774336d.el7.centos.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node2: Trying other mirror.
    node2: http://mirrors.163.com/centos/7/extras/x86_64/Packages/docker-common-1.13.1-53.git774336d.el7.centos.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node2: Trying other mirror.
    node2: http://mirrors.163.com/centos/7/os/x86_64/Packages/libcgroup-0.41-13.el7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node2: Trying other mirror.
    node2: http://mirrors.163.com/centos/7/os/x86_64/Packages/libsemanage-python-2.5-8.el7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node2: Trying other mirror.
    node2: http://mirrors.163.com/centos/7/extras/x86_64/Packages/oci-register-machine-0-6.git2b44233.el7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node2: Trying other mirror.
    node2: http://mirrors.163.com/centos/7/extras/x86_64/Packages/oci-systemd-hook-0.1.15-2.gitc04483d.el7.x86_64.rpm: [Errno 14] curl#6 - "Could not resolve host: mirrors.163.com; Unknown error"
    node2: Trying other mirror.

**Comment by pires** [comment]
This error is not related to this repo and the author must have mixed repos.

**Comment by sstoner** [comment]
change your Host's DNS server to 114.114.114.114
