### ISSUE TITLE
cloud-init stuck at docker-cache.service

### ISSUE THREAD

**Issue by xudifsd** [pires/kubernetes-vagrant-coreos-cluster#30]
Hi @pires 
I'm using this project to brought kubernetes up in my local machine, and `fleetctl list-machines` gives right output, but it failed to do `kubectl create`, output is

F0307 18:28:04.580672   56532 create.go:81] Post http://172.17.8.101:8080/api/v1beta1/pods?namespace=default: dial tcp 172.17.8.101:8080: connection refused

I sshed in master, and found it didn't start kubernetes api server, and I only find `flanneld setup-network-environment waiter.sh` in /opt/bin, also `ps -aux` says coreos-cloudinit is still running and stat is Ssl. I couldn't find where cloud-init's log exists, so I killed cloud-init and started it manually, it seems it stucks at docker-cache.service.

several line at end of output:
2015/03/07 10:27:56 Calling unit command "start" on "fleet.socket"'
2015/03/07 10:27:56 Result of "start" on "fleet.socket": done
2015/03/07 10:27:56 Calling unit command "start" on "fleet.service"'
2015/03/07 10:27:56 Result of "start" on "fleet.service": done
2015/03/07 10:27:56 Calling unit command "start" on "etcd-waiter.service"'
2015/03/07 10:27:56 Result of "start" on "etcd-waiter.service": done
2015/03/07 10:27:56 Calling unit command "start" on "docker-cache.service"'

I don't know how to fix this.

**Comment by pires** [comment]
Docker-cache is a registry docker container that will serve as a cache for
minions to use when pulling images from the Internet. It takes sometime to
download, depending on your Internet speed. Is it slow for you?

**Comment by xudifsd** [comment]
well, around 220Kb/s, kind of slow. how long it will take, and how should I determine if it's finished?

**Comment by pires** [comment]
* when docker ps show registry
* when kubernetes binaries are running

On Sat, Mar 7, 2015 at 10:55 AM, Di Xu <notifications@github.com> wrote:

> well, around 220Kb/s, kind of slow. how long it will take, and how should
> I determine if it's finished?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pires/kubernetes-vagrant-coreos-cluster/issues/30#issuecomment-77684079>
> .
>



-- 
Pires

**Comment by xudifsd** [comment]
ok, finished, thanks a lot
