### ISSUE TITLE
Support for CRI-O

### ISSUE THREAD

**Issue by remoe** [pires/kubernetes-vagrant-coreos-cluster#307]
Is it maybe interesting to switch to CRI-O ?

https://github.com/kubernetes-incubator/cri-o/blob/master/kubernetes.md

**Comment by pires** [comment]
It would be an interesting exercise. However, seems too much work for no gains at all. It could even make it harder to do certain things, like changing configuration to support private registries or self-signed TLS secured registries.

**Comment by pires** [comment]
hmmm, CoreOS brings Docker built-in. Docker is also used to run the "dumb" kubelet that will then run the static pods.

**Comment by bmcstdio** [comment]
@remoe last time I checked (couple of months ago) support for running CRI-O under CoreOS was very limited. Any idea if this has changed recently? I will try to have a look.

**Comment by pires** [comment]
@bmcstdio please, let's not do this.
