### ISSUE TITLE
The connection to the server localhost:8080 was refused!

### ISSUE THREAD

**Issue by gkoudjou** [pires/kubernetes-vagrant-coreos-cluster#316]
Hello,

I have a strange bug.

Everything is working fine with vagrant up.

But after some days running some containers, i have the following message when i tried any command involving kubectl

> core@master ~ $ kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?

I've tried to vagrant halt/up but i've an unexpected timeout exception on the up phase.

Could someone explain me what's going on and how to resolve it aside from completly destroy and create VM ?

Thanks

**Comment by pires** [comment]
You have changed your `~/.kube/config` and it's no longer pointing to the cluster created using this repo. If you fix that file, it will work again. There's no need for vagrant halt/up - IIRC that's not even supported.

**Comment by gkoudjou** [comment]
I didn't change anything in this directory.

Could you send me a sample config ?

**Comment by pires** [comment]
Well, something did because `localhost:8080` is not what's being defined [here](https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/Vagrantfile#L313-L316).
