### ISSUE TITLE
problem launch flannel docker0

### ISSUE THREAD

**Issue by MCyprien** [pires/kubernetes-vagrant-coreos-cluster#36]
Hello,
I have a issue with your last release, pods I launch are not connected in flannel network (10.244.X.X) but in docker0 network (10.1.X.X) so I can connect my pods from other nodes of the cluster

**Comment by MCyprien** [comment]
It works pretty well before, the issue come with the last commit I think

**Comment by AntonioMeireles** [comment]
@MCyprien thanks for reporting this. fix is already in my tree. should land here soonish.
