### ISSUE TITLE
cannot connect to master from OS X

### ISSUE THREAD

**Issue by rimusz** [pires/kubernetes-vagrant-coreos-cluster#4]
@pires 
$ export KUBERNETES_MASTER=http://172.17.8.101:8080
$ kubectl get minions
F0128 10:14:50.489095   52140 get.go:75] Get http://172.17.8.101:8080/api/v1beta1/minions?labels=&namespace=default: dial tcp 172.17.8.101:8080: connection refused

Could it be related to the latest k8s 0.9.1 version?

**Comment by pires** [comment]
Don't know how the hell this happened but it's working now. Good catch @rimusz, thank you so much!

**Comment by rimusz** [comment]
@pires glad to help :)
