### ISSUE TITLE
kube-apiserver crashlooping on master

### ISSUE THREAD

**Issue by hjfreyer** [pires/kubernetes-vagrant-coreos-cluster#43]
I've been banging my head against this for hours with no luck. Running from master, unchanged. Vagrant 1.7.2, virtualbox 4.3.24_OSEr98716, on Arch Linux.

When I ssh into the master I can see that kube-apiserver is starting up, then crashing, then getting restarted over and over. The log is not enlightening. When I start the server from the command line, rather than letting systemctl do it, everything is fine.

All the kubernetes services are failing, actually, but the API server is the one I've dug into.

Perhaps also related is the fact that I couldn't figure out how to stop it from constantly restarting. I added Restart=no to the "kube-apiserver.service" file and reloaded the configs, but it just kept looping, so something else is causing it to restart (and maybe causing it to die in the first place?)

Here's the log... can you reproduce?

Mar 18 02:11:28 master systemd[1]: Starting Kubernetes API Server...
Mar 18 02:11:28 master wget[2071]: --2015-03-18 02:11:28--  https://storage.googleapis.com/kubernetes-release/release/v0.10.1/bin/linux/amd64/kube-apiserver
Mar 18 02:11:28 master wget[2071]: Resolving storage.googleapis.com... 64.233.171.132, 64.233.171.132
Mar 18 02:11:28 master wget[2071]: Connecting to storage.googleapis.com|64.233.171.132|:443... connected.
Mar 18 02:11:28 master wget[2071]: HTTP request sent, awaiting response... 200 OK
Mar 18 02:11:28 master wget[2071]: Length: 19913056 (19M) [application/octet-stream]
Mar 18 02:11:28 master wget[2071]: Server file no newer than local file '/opt/bin/kube-apiserver' -- not retrieving.
Mar 18 02:11:28 master systemd[1]: Started Kubernetes API Server.
Mar 18 02:11:28 master kube-apiserver[2119]: I0318 02:11:28.675790    2119 plugins.go:70] No cloud provider specified.
Mar 18 02:11:28 master kube-apiserver[2119]: I0318 02:11:28.676366    2119 master.go:273] Setting master service IPs based on PortalNet subnet to "10.100.0.1" (read-only) and "10.100.0.2" (read-write).
Mar 18 02:11:28 master kube-apiserver[2119]: I0318 02:11:28.700728    2119 logs.go:40] [restful/swagger] listing is available at 172.17.8.101:8080/swaggerapi/
Mar 18 02:11:28 master kube-apiserver[2119]: I0318 02:11:28.713037    2119 logs.go:40] [restful/swagger] 172.17.8.101:8080/swaggerui/ is mapped to folder /swagger-ui/
Mar 18 02:11:28 master kube-apiserver[2119]: I0318 02:11:28.714246    2119 server.go:287] Serving read-only insecurely on 172.17.8.101:7080
Mar 18 02:11:28 master kube-apiserver[2119]: I0318 02:11:28.714561    2119 server.go:314] Serving securely on 172.17.8.101:8443
Mar 18 02:11:28 master kube-apiserver[2119]: I0318 02:11:28.714922    2119 server.go:342] Serving insecurely on 0.0.0.0:8080
Mar 18 02:11:30 master kube-apiserver[2119]: I0318 02:11:30.817309    2119 server.go:324] Using self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernetes/apiserver.key)
Mar 18 02:11:33 master systemd[1]: Stopping Kubernetes API Server...
Mar 18 02:11:33 master systemd[1]: kube-apiserver.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 18 02:11:33 master systemd[1]: Unit kube-apiserver.service entered failed state.
Mar 18 02:11:33 master systemd[1]: kube-apiserver.service failed.
Mar 18 02:11:36 master systemd[1]: Starting Kubernetes API Server...
Mar 18 02:11:36 master wget[2199]: --2015-03-18 02:11:36--  https://storage.googleapis.com/kubernetes-release/release/v0.10.1/bin/linux/amd64/kube-apiserver
Mar 18 02:11:36 master wget[2199]: Resolving storage.googleapis.com... 64.233.171.132, 64.233.171.132
Mar 18 02:11:36 master wget[2199]: Connecting to storage.googleapis.com|64.233.171.132|:443... connected.
Mar 18 02:11:36 master systemd[1]: Started Kubernetes API Server.
Mar 18 02:11:36 master wget[2199]: HTTP request sent, awaiting response... 200 OK
Mar 18 02:11:36 master wget[2199]: Length: 19913056 (19M) [application/octet-stream]
Mar 18 02:11:36 master wget[2199]: Server file no newer than local file '/opt/bin/kube-apiserver' -- not retrieving.
Mar 18 02:11:36 master kube-apiserver[2242]: I0318 02:11:36.495671    2242 plugins.go:70] No cloud provider specified.
Mar 18 02:11:36 master kube-apiserver[2242]: I0318 02:11:36.496323    2242 master.go:273] Setting master service IPs based on PortalNet subnet to "10.100.0.1" (read-only) and "10.100.0.2" (read-write).
Mar 18 02:11:36 master kube-apiserver[2242]: I0318 02:11:36.516886    2242 logs.go:40] [restful/swagger] listing is available at 172.17.8.101:8080/swaggerapi/
Mar 18 02:11:36 master kube-apiserver[2242]: I0318 02:11:36.542710    2242 logs.go:40] [restful/swagger] 172.17.8.101:8080/swaggerui/ is mapped to folder /swagger-ui/
Mar 18 02:11:36 master kube-apiserver[2242]: I0318 02:11:36.544579    2242 server.go:287] Serving read-only insecurely on 172.17.8.101:7080
Mar 18 02:11:36 master kube-apiserver[2242]: I0318 02:11:36.545339    2242 server.go:314] Serving securely on 172.17.8.101:8443
Mar 18 02:11:36 master kube-apiserver[2242]: I0318 02:11:36.545723    2242 server.go:342] Serving insecurely on 0.0.0.0:8080
Mar 18 02:11:37 master kube-apiserver[2242]: I0318 02:11:37.296141    2242 server.go:324] Using self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernetes/apiserver.key)
Mar 18 02:11:41 master systemd[1]: Stopping Kubernetes API Server...
Mar 18 02:11:41 master systemd[1]: kube-apiserver.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 18 02:11:41 master systemd[1]: Unit kube-apiserver.service entered failed state.
Mar 18 02:11:41 master systemd[1]: kube-apiserver.service failed.
Mar 18 02:11:44 master systemd[1]: Starting Kubernetes API Server...

**Comment by AntonioMeireles** [comment]
oops!. the good news is that i can reproduce, the bad news is that i have no clue yet on why this started to happen. digging. thanks for reporting.

**Comment by AntonioMeireles** [comment]
@hjfreyer issue identified and fixed. should be merged here later today. thanks for reporting and for your patience!

**Comment by pires** [comment]
It's fixed. Can you please confirm @hjfreyer?

**Comment by hjfreyer** [comment]
Looks like it's fixed. Thanks for the quick response!

**Comment by pires** [comment]
@hjfreyer I did screw this up. Can you please pull latest master and let me know how it goes for you?
