### ISSUE TITLE
eth1 use virtualbox dhcp

### ISSUE THREAD

**Issue by MCyprien** [pires/kubernetes-vagrant-coreos-cluster#45]
When CoreOS are launching they use the virtual box dhcp before setting static addresse. So we have multiple addresse on the card. The one used is 192.168.X.X and not 172.17.8.101 (for the master). It can be solved by disabling dhcp option in virtualbox.
I think it can be solved with something like that:
VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0
but i don't really know where can I put it...

**Comment by MCyprien** [comment]
There is another problem when trying to connect to master using kubectl with connection refused but it can be due to this issue so I aml not opening another issue

**Comment by pires** [comment]
@MCyprien yes, you need to disable whatever DHCP server you may have running. This is something related to each provider and host configuration. I'll add something to the docs about it.

The command you refer to should be run on your host once and doesn't need to be put into any of the files in this repository.
