### ISSUE TITLE
VM use DHCP instead of static IP adresses as expected

### ISSUE THREAD

**Issue by ggarson** [pires/kubernetes-vagrant-coreos-cluster#47]
Hi,

before the commit 7f3370968c962ea2d733314fddc2b336b305f358 everything was OK. 

Now when I deploy a cluster with virtualbox provider (I configured a DHCP serveur inside virtualbox in the subnet 172.17.8.x-49/99), nodes use IP provided by the DHCP instead of 172.17.8.101 (master) and so on for minions.

P.S. I don't used the sync file, so all is by default.

Tell me if you need more information to reproduce the problem.

**Comment by AntonioMeireles** [comment]
@ggarson :cry:  
afaict none of the changes at the above commit in the Vagrantfile should ever change the way the vagrant/hypervisor networking was going on.

so, the issue persists if you just disable (per the README) the 'native' VirtualBox DHCP ? ( `VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0` )

**Comment by ggarson** [comment]
In fact there is no issue if I disable it (I did it as a workaround) but before it was working event if the DHCP was enabled.

In fact I use another virtual machine (or more) in virtualbox in the subnet 172.18.8.0 to access directly to my coreos host. And there virtual machines are configured to use a dhcp.

So it's not really an issue but more precisely a regression. Someone was faced of the same problem than me on irc chan of Kubernetes.

**Comment by pires** [comment]
@ggarson @AntonioMeireles there are many issues coming up with that merge and I'm currently removing them, but since the PR had so many things - my bad! - it's hard to revert. Am working on it as we speak.

**Comment by AntonioMeireles** [comment]
i believe you i just have no freaking idea of what triggered this change of behaviour. will digg. (btw if you use old CoreOS alpha images - issue persists ? (just to make sure that this isn't some upstream change)

**Comment by ggarson** [comment]
I use the last alpha images for days and I was only a problem this morning after the git pull... I reinstall my clusters few times by day

**Comment by pires** [comment]
@ggarson working on a hotfix as we speak. Please bear with me ;-)

**Comment by ggarson** [comment]
@pires don't worry, you are doing a great job ;)

**Comment by pires** [comment]
@ggarson thanks for your kind words. Can you please try it out now and let me know?

**Comment by ggarson** [comment]
It's OK for the DHCP issue.

Thanks @pires

**Comment by pires** [comment]
Awesome @ggarson! Thanks for your feedback man.
