### ISSUE TITLE
Document forwarding of external traffic from host to k8s services

### ISSUE THREAD

**Issue by hjfreyer** [pires/kubernetes-vagrant-coreos-cluster#48]
Here's my setup:
- I have a personal Arch Linux server for NAS, personal HTTP, backup, bitcoin node, etc.
- I want to use k8s to make my configuration as stateless as possible. If my server died tomorrow, I should be able to restore my data and get all my programs up and running with a few shell scripts. Also, security through VMs/containerization.
- I want to map incoming connections on my host (e.g. http) to k8s services.

My current almost-solution is to have a single minion setup, include the minion's static IP in the service definitions, and use iptables rules on the host to forward traffic coming in on certain ports to the minion. The reason I say this "almost" works is that the default Vagrantfile makes everything a "private network", so communication between the host and minions is fine, but forwarding external traffic to the minion gets blocked.

(The reason it gets blocked is that the network interface on the guest OS is configured without a gateway, so traffic from the host IP is expected on that interface, but if the source IP comes from the outside world, Linux sees it as being outside the interface's subnet and drops it on the floor.)

I worked around this hackily by adding a unit to node.yaml which sets a default gateway on the interface used to talk to the host, but it seems that solution has started interfering with etcd, so I'm looking for a more robust one.

I've considered:
* Making the networks be public_networks, but that behaves a bit weirdly (nodes start querying my LAN's DHCP server).
* Running kube-proxy on the host, but then I've got a not-super-mature piece of software exposed to the outside world running as root on the host which would kinda defeat the purpose security-wise.
* Running a third VM with a public_network and kube-proxy on it, so network weirdness gets hidden from the minions, but that would require some fiddling.

Any established practices for this?

**Comment by pires** [comment]
Not an established practice, but it's as easy as adding a second NIC to the node you want (or nodes) and set an IP address that belongs to your LAN. Here's what I did:
* In `Vagrantfile` define a fake MAC address for the node(s) where you'll have services exposed to your LAN
* Set-up a DHCP server on your LAN that will set the IP address you want for said fake MAC address - DHCP server is needed because I haven't found a way to set DNS & gateway on `Vagrantfile`

What do you think?

**Comment by pires** [comment]
@hjfreyer please be sure to check #50 cause it may have impact on your tests.

**Comment by hjfreyer** [comment]
This seems to work well enough! For some reason I was thinking double-NATing (first at my router, then within my box) felt more "secure", but really it's just unnecessary overhead. 

Thanks for the tip!

**Comment by pires** [comment]
@hjfreyer Glad it worked out. OK to close then?
