### ISSUE TITLE
Using https://get.k8s.io is outdated

### ISSUE THREAD

**Issue by onemorehill** [pires/kubernetes-vagrant-coreos-cluster#49]
Why are projects such as this one still using https://get.k8s.io to derive the latest releases of kubenetes. It looks like it hasn't been update in a while as kube is now 0.12.0.
Oh and since this is my first communication - you people are doing some great work here :)

**Comment by pires** [comment]
@onemorehill I've replaced the (not so) _smart_ way of telling the latest version with a hardcoded default version for `KUBERNETES_VERSION` variable in the `Vagrantfile`. Right now, it's `0.13.1` which as been tested by me.

Thank you for your report!
