### ISSUE TITLE
k8s services have 10.100.x.y addresses

### ISSUE THREAD

**Issue by wkharold** [pires/kubernetes-vagrant-coreos-cluster#50]
After vagrant up the kubernetes and kubernetes-ro services IP fields are 10.100.0.2 and 10.100.0.1 respectively. Those addresses aren't pingable from either the host machine or from the master.

**Comment by pires** [comment]
Service addresses are never pingable. See more details about services [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md#portals-and-service-proxies).

**Comment by pires** [comment]
Nonetheless, accessing read-only service with `curl http://${KUBERNETES_RO_SERVICE_HOST}:${KUBERNETES_RO_SERVICE_PORT}` is not possible in any of the nodes. Looking at it!

**Comment by pires** [comment]
Bug in Kubernetes `0.13.x`. With `0.12.2` it works. See https://github.com/GoogleCloudPlatform/kubernetes/issues/5647

**Comment by pires** [comment]
@wkharold try this `KUBERNETES_VERSION=0.12.2 vagrant up` and then re-test what you're doing.

**Comment by wkharold** [comment]
@pires with KUBERNETES_VERSION=0.12.2 attempting to curl kubernetes-ro times out. Doing
iptables -t nat -L yields: https://gist.github.com/wkharold/bd2fc9065e2b9b7dc433

**Comment by pires** [comment]
@wkharold works here.
```
core@node-01 ~ $ curl http://10.100.0.1
{
  "paths": [
    "/api",
    "/api/v1beta1",
    "/api/v1beta2",
    "/healthz",
    "/logs/",
    "/metrics",
    "/static/",
    "/swagger-ui/",
    "/swaggerapi/",
    "/validate",
    "/version"
  ]
```

**Comment by wkharold** [comment]
@pires yes, works for me as well on a minion, just not on the master. I assume that's working as designed. Thanks.

**Comment by pires** [comment]
@wkharold yes, `kube-proxy` is not running on the master, so it's expect not to access services.
