### ISSUE TITLE
Missing closing `"` on line 4 of kubLocalSetup

### ISSUE THREAD

**Issue by wkharold** [pires/kubernetes-vagrant-coreos-cluster#51]

**Comment by AntonioMeireles** [comment]
CC: @pires.  @wkharold this is already fixed in [my](https://github.com/AntonioMeireles/kubernetes-vagrant-coreos-cluster) tree. the bad news is that atm things have diverged a bit. only cherry picks or manual merges will do...

**Comment by pires** [comment]
Thanks @wkharold.

**Comment by pires** [comment]
@AntonioMeireles yeah, I understand you want to keep your stuff and I'm totally OK with you going with it. Will keep an eye and steal some stuff from time to time ;-) long live OSS
