### ISSUE TITLE
Make VM disks configurable

### ISSUE THREAD

**Issue by pires** [pires/kubernetes-vagrant-coreos-cluster#56]
VM disks are not configurable as of the moment. We need this so we don't end up filling disks with more aggressive testbeds.

/cc @albertocsm

**Comment by AntonioMeireles** [comment]
fwiw i wouldn't not even try again to fix this ... [i tried before] ...

- it's hypervisor dependent
- vagrant would by default on update destroy the extra disks. 

the simplest IMHO is to take advantage of the plugable NFS mounts machinery to make data persistent....

**Comment by pires** [comment]
This issue is not related to persistent data but rather to ephemeral data that we want to be able to store during our testbed lifecycle (meaning before `vagrant destroy`).

**Comment by AntonioMeireles** [comment]
still. the easiest way are NFS mounts :-). we already can do that for free. one can  manualy extend the partitions but ... tricky.

**Comment by pires** [comment]
NFS mounts it is.
