### ISSUE TITLE
DNS integration - how to access DNS server or other services?

### ISSUE THREAD

**Issue by frosenberg** [pires/kubernetes-vagrant-coreos-cluster#60]
I ran your scripts, works perfectly fine so far.

However, I have a question on the DNS integration:
```
florian@Florians-MacBook-Pro:~/Code$ kubectl get services
NAME                LABELS                                                              SELECTOR            IP                  PORT
kube-dns            k8s-app=kube-dns,kubernetes.io/cluster-service=true,name=kube-dns   k8s-app=kube-dns    10.100.0.10         53
kubernetes          component=apiserver,provider=kubernetes                             <none>              10.100.0.2          443
kubernetes-ro       component=apiserver,provider=kubernetes                             <none>              10.100.0.1          80
```

I see those services running now but I have no way of accessing the DNS server for example. The following times out (assuming I have `webui` as a service deployed):

```
florian@Florians-MacBook-Pro:~/Code$ dig @10.100.0.10 +short webui.pires-kube
;; connection timed out; no servers could be reached
```

Actually, every ping to any of the service IPs times out. I presume this means that all k8s services are inaccessible. Is there any step I'm missing?

**Comment by pires** [comment]
All k8s services are only accessible from inside the cluster. Unless you set publicIPs flag to an IP address you can access from your host.

**Comment by pires** [comment]
Please run the following
```
vagrant ssh node-01
dig @10.100.0.10 +short webui.default.pires-kube
```

`default` is the namespace being used, which in case it's not explicitly set defaults to `default`.

**Comment by frosenberg** [comment]
Thanks. I was missing the default part. I should have better RTFM :)

**Comment by pires** [comment]
Great @frosenberg.

**Comment by frosenberg** [comment]
Is there a way to remove the namespace `default` or set it to something else? I could not find anything in the vagrant file.

**Comment by pires** [comment]
@frosenberg I've not yet had the need for [namespaces](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/namespaces.md). But feel free to open a PR.
