### ISSUE TITLE
Replace env vars in ~/.bash_profile with sed

### ISSUE THREAD

**Issue by pires** [pires/kubernetes-vagrant-coreos-cluster#65]
This is to be implemented in `setup` script.

**Comment by sandric** [comment]
Maybe it is better to create separate .sh file for env variables instead of .bash_profile? For example if user uses fishshell(as I do), or zsh? I think there's a point in moving it out to separate file.

**Comment by pires** [comment]
For as long as it's simple to any user I'm OK with it. At first, we had
said separate file, but a lot of novice users forgot to run it, etc. So I
moved to this approach.

I'm always eager for PRs

**Comment by errm** [comment]
Could this be implemented as a script in /etc/profile.d/

**Comment by pires** [comment]
@errm I don't believe so.

**Comment by pires** [comment]
Fixed by #94
