### ISSUE TITLE
Failed to mutate etcd when using mutator

### ISSUE THREAD

**Issue by l3ubbleman** [pires/kubernetes-vagrant-coreos-cluster#72]
![screen shot 2015-04-24 at 3 15 21 pm](https://cloud.githubusercontent.com/assets/6844972/7326606/d1cb4080-ea94-11e4-8cea-637ebf16a82d.png)

On startup the k8s-dns pod containers work fine, but usually when I delete them and the controller brings it back up, I get the above message when I enter "kubectl log <k8s-dns pod> kube2sky" and for "kubectl log <k8s-dns pod> skydns" I get:

![screen shot 2015-04-24 at 3 19 15 pm](https://cloud.githubusercontent.com/assets/6844972/7326690/6384b808-ea95-11e4-8b25-4bce71782fe1.png)

**Comment by l3ubbleman** [comment]
Not sure if it's related but I can't curl the dns records being set. I can curl the ones they're being mapped to.

![screen shot 2015-04-24 at 3 31 49 pm](https://cloud.githubusercontent.com/assets/6844972/7326919/0e634d4c-ea97-11e4-8240-7d44ae224f44.png)

**Comment by pires** [comment]
That's weird, the first logs indicate you lost communication to `etcd` but the second ones show everything working OK. Now I guess you're facing #74. Will look into it during the weekend.

**Comment by l3ubbleman** [comment]
The first logs were from me deleting the pod and the controller bringing them up. The second logs were from the pods being created by bringing up the cluster through vagrant

**Comment by pires** [comment]
Another thing in the first logs, the IP address of the `dns` pod is not a flannel address. Did you change anything?

**Comment by l3ubbleman** [comment]
I have just retried with a clone of your repo again. The same thing happens, however it was after I deleted the pod twice this time that the error happened again.

**Comment by pires** [comment]
This is probably a `kube2sky` bug.

**Comment by pires** [comment]
Why are you deleting the pod, anyway? I wasn't able to reproduce this in a way that I believe will affect regular users.

**Comment by l3ubbleman** [comment]
It was for testing if the dns pod goes down, that it would properly bring it back up again. If that pod goes down, wouldn't it prevent me from using dns records to look up my services?

![screen shot 2015-04-24 at 3 22 46 pm](https://cloud.githubusercontent.com/assets/6844972/7372562/73282134-ed95-11e4-9d12-d693c4d48d56.png)
And the logging for kube2sky is misleading because it seems to say that it maps the dns address to the ip and port when it only maps to the ip

**Comment by pires** [comment]
@l3ubbleman can you open an issue on the `kube2sky` project and link this issue? I believe it's their issue.

**Comment by l3ubbleman** [comment]
This seems to be fixed with #75

**Comment by pires** [comment]
Awesome @l3ubbleman
