### ISSUE TITLE
Ethernet device named ens34 instead of eth1 on Fusion

### ISSUE THREAD

**Issue by ericgray** [pires/kubernetes-vagrant-coreos-cluster#76]
I was able to successfully get this working on VMware Fusion along with the Kubernetes Guestbook example.  Strange networking issues due to cloud-config files referring to interface eth1, which is correct on VirtualBox, but not on Fusion. 

I modified `master.yaml` and `node.yaml` to refer to ens34 instead of eth1.  Works.

It may be helpful to find a way to conditionally use the applicable interface name.

**Comment by pires** [comment]
Hi @ericgray, thank you so much for getting back with this valuable information. I'll be working on updating documentation and a way to fix this, but only after I understand why CoreOS names the interfaces that way. Could you please provide more details?

**Comment by ericgray** [comment]
Looking at the systemd journal from CoreOS, the following line is relevant:

Apr 29 23:21:01 localhost kernel: e1000 0000:02:01.0 ens33: renamed from eth0

It appears that systemd has a new device naming convention:

http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

Perhaps differences in the virtual hardware attributes exposed by VirtualBox and by Fusion cause different policies to be triggered.

Eric



On Apr 29, 2015, at 4:16 PM, Paulo Pires <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @ericgray<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ericgray&d=AwMCaQ&c=Sqcl0Ez6M0X8aeM67LKIiDJAXVeAw-YihVMNtXt-uEs&r=ECuKpK0WP3osM9NTxH7c_Q&m=mJUfkxuKRPjn5UbqrVjBjhEN2DsB7oDCBcbfpQU4rhk&s=-nlWgR5h7fi8m7KH18xqGuQ4j6QIbVdOBSoXSU_l_eI&e=>, thank you so much for getting back with this valuable information. I'll be working on updating documentation and a way to fix this, but only after I understand why CoreOS names the interfaces that way. Could you please provide more details?

**Comment by pires** [comment]
Thank you @ericgray. I'll need to think of a way to workaround this, because right now I have no idea on how to dynamically get/set this information.

**Comment by pires** [comment]
Fixed by #82.
