### ISSUE TITLE
Can't resolve anything via DNS after vagrant reload

### ISSUE THREAD

**Issue by reasn** [pires/kubernetes-vagrant-coreos-cluster#77]
Thanks for this awesome project!
Preliminary remark: During the last days I followed up on https://github.com/pires/kubernetes-vagrant-coreos-cluster/issues/74 and cloned your master branch just a few hours ago.

```
git clone git@github.com:pires/kubernetes-vagrant-coreos-cluster.git
cd kubernetes-vagrant-coreos-cluster
vagrant up
source ~/.bash_profile
kubectl get pods,services,rc
```
Looks like everything is alright.

Now I spin up a stock nginx and a corresponding service from
https://gist.github.com/reasn/bfbf9425606873b58021 like so:
```
kubectl create -f https://gist.githubusercontent.com/reasn/bfbf9425606873b58021/raw/6e86a84c26c700c2e47dd5903d5624a1695293cb/svc-nginx.yml
kubectl create -f https://gist.githubusercontent.com/reasn/bfbf9425606873b58021/raw/5906a19ba33eb28cfeb9db088971e4bf5e03907e/rx-nginx.yml
kubectl get pods,services,rc
```
If I now ```vagrant ssh node-01``` and ```curl 10.244.62.2``` (IP of the nginx pod) I get a response from nginx.
Same with the IP of the nginx service.

But if I ```curl svc-nginx.default.k8s.local``` curl can't resolve the host.

The same holds if I ```docker exec```into the nginx container (in my case on node-02) and try to ```ping svc-nginx.default.k8s.local``` (Chose ```ping``` because the nginx stock container has neither ```curl``` nor ```dig```).

I could not find out what I might have done wrong.
It seems to me that something with skydns is not working properly.

**Update (2015-04-30 15:10 CEST):** I might've ```vagrant reload```ed the machine in between, currently investigating this

**Update (2015-04-30 15:31 CEST):** The reason is the ```vagrant reload```. That seems to kill the DNS

**Comment by pires** [comment]
What's the error when you ping? Services are not pingable but you should have the address resolved. Try nslookup

**Comment by reasn** [comment]
Thanks for your response!
```ping svc-nginx.default.k8s.local```inside the nginx-container returns (after a while):
```PING svc-nginx.default.k8s.local (10.100.0.3): 56 data bytes
^C--- svc-nginx.default.k8s.local ping statistics ---
126 packets transmitted, 0 packets received, 100% packet loss
```
That means the resolve worked.
I have no idea why it did work now.

But if I ```vagrant reload```things it stops to work (I might have done that before as well, sorry for that. I fixed the description).

If I - after having issued ```vagrant reload``` once - do the same ping inside the nginx container again I get ```ping: unknown host```.

To make my checks more comprehensive I also spun up one of our ubuntu machines to be able to use curl and nslookup:
```
root@rpc-dev-node-5iu2n:/www# curl svc-nginx.default.k8s.local 
curl: (6) Could not resolve host: svc-nginx.default.k8s.local
```

**Comment by reasn** [comment]
Can confirm, it's the reload, just updated the issue

**Comment by pires** [comment]
@reasn thank you for debugging. I'm providing a fix today if work allows!

**Comment by reasn** [comment]
Wow. Awesome!
