### ISSUE TITLE
Upgrade to 0.17.0

### ISSUE THREAD

**Issue by Hikariii** [pires/kubernetes-vagrant-coreos-cluster#89]
A new version of kubernetes has been released.
https://github.com/GoogleCloudPlatform/kubernetes/releases/tag/v0.17.0
All parts of kubernetes and kubectl are released with v0.17.0

**Comment by pires** [comment]
@Hikariii I already have a PR ready for that, I'm just waiting the release notes to get out. Have had enough goose chases in the past for not having those.

**Comment by pires** [comment]
Initial tests validate my changes are working, though.

**Comment by Hikariii** [comment]
I will test my windows setup today. I was wondering how we could make sure a new version isn't breaking, but I guess release notes and a lot of testing are the only way.

**Comment by pires** [comment]
@Hikariii we can't. Even the Kubernetes guys who have a lot o E2E tests can't guarantee that one.
