### ISSUE TITLE
Cluster does not work behind HTTP proxy

### ISSUE THREAD

**Issue by alexei-led** [pires/kubernetes-vagrant-coreos-cluster#92]
I'm trying to run a Kubernetes cluster behind corporate HTTP proxy. I'm also using vagrant-proxyconf plugin, and define http/s proxy and no_proxy hosts there.
Custer nodes fail to start with "Failed to start Docker Application Container Engine." error.

**Comment by pires** [comment]
@alexei-led there's a lot of _downloading_ happening when bootstrapping the VMs and when provisioning pods/containers. You probably fixed the first but need to [fix the second as well](https://coreos.com/docs/launching-containers/building/customizing-docker/#use-an-http-proxy).

I'm more than happy to review a PR that handles this.

**Comment by alexei-led** [comment]
Beside configuring proxy for proxyconf vagrant plugin, I've also tried to run a provision shell script, which checks if my machine is located behind proxy and then if Vagrant box is running CoreOS creates there required http-proxy.conf file (as described in documentation, you've sent). 
The problem is that this provision shell script is executed only for master box and not for nodes. 
Any idea why?

**Comment by pires** [comment]
@alexei-led it will depend on where in the `Vagrantfile` you have the call to said script. If you want, please open a PR with your current work so that I can review it and help you as you go.
