### ISSUE TITLE
Private repository pull failed

### ISSUE THREAD

**Issue by jdojff** [pires/kubernetes-vagrant-coreos-cluster#97]
Hello, I'm using private repository to store docker images. I have setup cluster also providing docker cfg. When starting pods I receive:
myservice registry.my.com/user/myservice Waiting image pull failed for registry.my.com/user/myservice, this may be because there are no credentials on this request. details: (Authentication is required.)

However, I'm able to pull these images directly with docker on master and node.

**Comment by pires** [comment]
Please share actual logs.

**Comment by jdojff** [comment]
Not sure which one..?
docker events only shows gcr.io/google_containers/pause:0.8.0 image container being created and started, which itself does not log anything.
There is no sign of myservice image pulling and starting..

**Comment by pires** [comment]
Where did you see the errors you described above?

**Comment by janroos** [comment]
Same issue here. It started today after I updated. Using on Windows through Vagrant. Probably got new versions of your code and new CoreOS (681.0.0) at the same time.

After doing successful docker login, I have copied the .dockercfg from /home/core to / and /root and /var/lib/kubelet. Nothing seems to help. When I ssh to node and do docker pull, it works.

Some logs from node's journalctl

May 19 13:40:33 node-01 dockerd[5649]: time="2015-05-19T13:40:33Z" level=info msg="GET /images/ent.changed.com:5000/firewall:latest/json"
May 19 13:40:33 node-01 dockerd[5649]: time="2015-05-19T13:40:33Z" level=info msg="+job image_inspect(ent.changed.com:5000/firewall:latest)"
May 19 13:40:33 node-01 dockerd[5649]: No such image: ent.changed.com:5000/firewall:latest
May 19 13:40:33 node-01 dockerd[5649]: time="2015-05-19T13:40:33Z" level=info msg="-job image_inspect(ent.changed.com:5000/firewall:latest) = ERR (1)"
May 19 13:40:33 node-01 dockerd[5649]: time="2015-05-19T13:40:33Z" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: ent.changed.com:5000/firewall:latest"
May 19 13:40:33 node-01 dockerd[5649]: time="2015-05-19T13:40:33Z" level=error msg="HTTP Error: statusCode=404 No such image: ent.changed.com:5000/firewall:latest"
May 19 13:40:33 node-01 kubelet[1442]: E0519 13:40:33.144374    1442 kubelet.go:1767] Cannot get host IP: host IP unknown; known addresses: []
May 19 13:40:33 node-01 dockerd[5649]: time="2015-05-19T13:40:33Z" level=info msg="GET /containers/json"
May 19 13:40:33 node-01 dockerd[5649]: time="2015-05-19T13:40:33Z" level=info msg="+job containers()"
May 19 13:40:33 node-01 dockerd[5649]: time="2015-05-19T13:40:33Z" level=info msg="-job containers() = OK (0)"
May 19 13:40:33 node-01 dockerd[5649]: time="2015-05-19T13:40:33Z" level=info msg="GET /containers/json"


'kubectl get events' does not have much:
Tue, 19 May 2015 13:34:02 +0000   Tue, 19 May 2015 13:48:34 +0000   88        firewall-scqcn          Pod       spec.containers{firewall}           failed    {kubelet 172.17.8.102}   Failed to pull image "ent.changed.com:5000/firewall:latest": Authentication is required.

**Comment by janroos** [comment]
More logs from node's journalctl.

May 19 13:53:05 node-01 dockerd[5649]: time="2015-05-19T13:53:05Z" level=info msg="-job pull(ent.changed.com:5000/firewall, latest) = ERR (1)"
May 19 13:53:05 node-01 kubelet[1442]: W0519 13:53:05.378777    1442 manager.go:1403] Failed to pull image "ent.changed.com:5000/firewall:latest" from pod "firewall-scqcn_default" and container "firewall": Authentication is required.
May 19 13:53:05 node-01 kubelet[1442]: I0519 13:53:05.378766    1442 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"firewall-scqcn", UID:"0bf84892-fe1e-11e4-822d-0800270db324", APIVersion:"v1beta3", ResourceVersion:"32722", FieldPath:"spec.containers{firewall}"}): reason: 'failed' Failed to pull image "ent.changed.com:5000/firewall:latest": Authentication is required.

**Comment by pires** [comment]
Please see https://github.com/GoogleCloudPlatform/kubernetes/issues/7954

**Comment by pires** [comment]
@janroos I've had issues with something like this before, and in the end it wasn't related to `docker` stuff at all but rather the `kubelet` not being able to read `.dockercfg`. I've just merged @AntonioMeireles 93cebf8 hoping to fix it. Can you please retry with it and let us know?

**Comment by janroos** [comment]
Thanks Pires! Tried but unfortunately it did not help. The .dockercfg gets copied from host to /home/core and to /root. 

Works when I manually do docker pull or sudo docker pull

**Comment by janroos** [comment]
For others that are struggling with this. Here's my current workaround:

Run this on all nodes:
journalctl | grep -o 'Failed to pull image "[^"]*' | grep -o ent.ch**|sort -u|xargs -L1 docker pull
sudo systemctl restart docker

Explanation:
It greps the logs for errors pulling from private registry (in my case registry address starting with "ent.ch"), filters out duplicates and then runs docker pull for each missing image.

After this I restart docker daemon - so it starts to re-deploy immediately.

**Comment by pires** [comment]
This is something with the kubelet. Can you please share logs?

**Comment by janroos** [comment]
Maybe worth to note here is that I am using self-signed certificate. Here's how I install it on every coreos host:

cp self-signed.pem /etc/ssl/certs/
sudo update-ca-certificates
sudo systemctl restart docker

After this was done, I ran on master:
kubectl create -f firewall-controller.yaml

This is the whole log of a node.
https://dl.dropboxusercontent.com/u/57064515/node.log

Search for "firewall"

**Comment by pires** [comment]
```
May 21 08:40:44 node-01 dockerd[5595]: time="2015-05-21T08:40:44Z" level=info msg="-job image_inspect(ent.coolbet.com:5000/firewall) = ERR (1)"
May 21 08:40:44 node-01 dockerd[5595]: time="2015-05-21T08:40:44Z" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: ent.coolbet.com:5000/firewall"
May 21 08:40:44 node-01 dockerd[5595]: time="2015-05-21T08:40:44Z" level=error msg="HTTP Error: statusCode=404 No such image: ent.coolbet.com:5000/firewall"
```

This is it. I've seen this before and @erictune at the time told me what it was - IIRC something with the `kubelet`. I will try and hunt for what fixed it.

**Comment by MaxDaten** [comment]
Maybe this is a hint: http://ask.projectatomic.io/en/question/179/authenticating-kubernetes-for-private-images-on-docker-hub/
according to the reply, the .dockercfg has to be in the working directory of kubelet.

To get the cwd I executed on a node:
```
core@node-02 ~ $ sudo ls -ld /proc/$(pidof kubelet)/cwd
lrwxrwxrwx 1 root root 0 Jun  1 13:18 /proc/999/cwd -> /
```

so it`s the root. 

see #108 for an example kubelet config. With changing the working directory of the kubelet, the kubelet is able to pull private repositories when authenticated with .dockercfg.

**Comment by analytik** [comment]
For people who still have a problem with this, try adding `https://` to your `.dockercfg`. I found this to work for me:
```
{
	"hub.example.com:1024": {
		"auth": "asdf=",
		"email": "example@example.com"
	},
	"https://hub.example.com:1024": {
		"auth": "asdf=",
		"email": "example@example.com"
	}
}
```
Without the https block, I was logged in from console (core user), but kubelet would throw auth errors (even when the `.dockercfg` file in its working directory, `/root/`, exists and is readable).

**Comment by pires** [comment]
@analytik would you be so kind and provide a PR with an update to `README.md` with your conclusion in the `Troubleshooting` section?

**Comment by erictune** [comment]
Or put it in: the "Configuring Nodes to Authenticate to a Private Registry"
section of "docs/images.md".
