### ISSUE TITLE
 kube-apiserver wupiao not getting response from etcd2

### ISSUE THREAD

**Issue by heytrav** [pires/kubernetes-vagrant-coreos-cluster#98]
This seems to happen whenever I've shutdown vagrant and try to restart it again with `vagrant up`.

* `kube-apiserver` hangs on `wupiao` dependency endlessly
```
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/etc/systemd/system/kube-apiserver.service; static; vendor preset: disabled)
   Active: activating (start-pre) since Tue 2015-05-19 22:28:47 ; 1min 15s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 3500 ExecStartPre=/usr/bin/chmod +x /opt/bin/kube-apiserver (code=exited, status=0/SUCCESS)
  Process: 3489 ExecStartPre=/usr/bin/wget -N -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/v0.17.0/bin/linux/amd64/kube-apiserver (code=exited, status=0/SUCCESS)
  Process: 3485 ExecStartPre=/usr/bin/mkdir -p /opt/bin (code=exited, status=0/SUCCESS)
  Control: 3504 (wupiao)
   Memory: 332.0K
   CGroup: /system.slice/kube-apiserver.service
           └─control
             ├─3504 /bin/bash /opt/bin/wupiao 172.17.8.101:2379/v2/machines
             └─3664 sleep 1

May 19 22:29:53 master wupiao[3504]: .
May 19 22:29:54 master wupiao[3504]: .
May 19 22:29:55 master wupiao[3504]: .
May 19 22:29:56 master wupiao[3504]: .
May 19 22:29:57 master wupiao[3504]: .
May 19 22:29:58 master wupiao[3504]: .
May 19 22:29:59 master wupiao[3504]: .
May 19 22:30:00 master wupiao[3504]: .
May 19 22:30:01 master wupiao[3504]: .
May 19 22:30:02 master wupiao[3504]: .
```

* `etcd2` seems to be up and listening on `http://localhost:2379` while `wupiao` is pinging `http://172.17.8.101:2379`

```
core@master /etc/systemd/system $ systemctl status etcd2
● etcd2.service - etcd2
   Loaded: loaded (/usr/lib64/systemd/system/etcd2.service; static; vendor preset: disabled)
   Active: active (running) since Tue 2015-05-19 22:18:31 ; 11min ago
 Main PID: 2066 (etcd2)
   Memory: 12.1M
   CGroup: /system.slice/etcd2.service
           └─2066 /usr/bin/etcd2

May 19 22:18:32 master etcd2[2066]: 2015/05/19 22:18:32 raft: 75263048b09334ce received vote from 75263048b09334ce at term 6
May 19 22:18:32 master etcd2[2066]: 2015/05/19 22:18:32 raft: 75263048b09334ce became leader at term 6
May 19 22:18:32 master etcd2[2066]: 2015/05/19 22:18:32 raft.node: 75263048b09334ce elected leader 75263048b09334ce at term 6
May 19 22:18:32 master etcd2[2066]: 2015/05/19 22:18:32 etcdserver: published {Name:98f562dff4b14da5a208cae0dc963fb5 ClientURLs:[http://localhost:2379 http://localhost:4001]} to cluster a741eabc2549d13f
May 19 22:20:17 master etcd2[2066]: 2015/05/19 22:20:17 etcdserver: start to snapshot (applied: 110011, lastsnap: 100010)
May 19 22:20:17 master etcd2[2066]: 2015/05/19 22:20:17 etcdserver: compacted log at index 110011
May 19 22:20:17 master etcd2[2066]: 2015/05/19 22:20:17 wal: segmented wal file /var/lib/etcd2/member/wal/000000000000000b-000000000001adbc.wal is created
May 19 22:20:17 master etcd2[2066]: 2015/05/19 22:20:17 etcdserver: saved snapshot at index 110011
May 19 22:20:31 master etcd2[2066]: 2015/05/19 22:20:31 filePurge: successfully removed file /var/lib/etcd2/member/snap/0000000000000002-000000000000ea66.snap
May 19 22:20:31 master etcd2[2066]: 2015/05/19 22:20:31 filePurge: successfully removed file /var/lib/etcd2/member/wal/0000000000000006-000000000000ea67.wal
```

**Comment by pires** [comment]
I do not see how is it possible to just listen on `localhost`, https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/master.yaml#L23.

**Comment by heytrav** [comment]
I'm not really sure why either. When I build the VMs everything works ok. However this seems to happen whenever I `vagrant halt` and then later `vagrant up`. At first I was wondering why it just seemed to wait forever to bring up the master node. When I  ssh into master and start looking at `journalctl -f`  and `systemctl status etcd` output, that's what I see.

**Comment by pires** [comment]
The only place we run `halt` hooks is https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/Vagrantfile#L267.

**Comment by heytrav** [comment]
Ok, sorry I'm a bit confused. Mainly because this had always worked in the past. I routinely run `vagrant halt` to shut down the kubernetes VMs on my laptop. Is `halt` not supposed to be used?

**Comment by wstrange** [comment]
I also see issues when doing a vagrant halt / vagrant up.   

The master hangs forever trying to boot. I see this with journalctl:

May 20 02:48:50 master locksmithd[487]: Unlocking old locks failed: [etcd.service etcd2.service] are inactive. Retrying in 1m20s. 

Which looks like some kind of lock file issue.

**Comment by heytrav** [comment]
@wstrange what do you see when you do `journalctl -f kube-apiserver`?

**Comment by pires** [comment]
On systems like Kubernetes, a shutdown is catastrophic. In case of a `minion`, it's just removed for instance.

Anyway, care to show me the contents of the cloud-config that are inside `master` and `minion` after `halt` and `up`, @wstrange @heytrav?

**Comment by heytrav** [comment]
After `vagrant halt`/`vagrant up`. It hangs waiting for master to become ready and never gets to the minions.  The cloud-config.yml file for the master is [here](https://gist.github.com/heytrav/6ae2f96fda07576d731b).

**Comment by pires** [comment]
@heytrav I want `/var/lib/coreos-vagrant/vagrantfile-user-data`.

**Comment by heytrav** [comment]
Looks like it doesn't exist
```
core@master ~ $ cat /var/lib/coreos-vagrant/vagrantfile-user-data
cat: /var/lib/coreos-vagrant/vagrantfile-user-data: No such file or directory
```

So basically if I understand correctly, once a Vagrant-Kubernetes cluster has been created, it can't be shutdown again? I'd been routinely when I'm not developing stuff with it.

**Comment by pires** [comment]
I've linked the code that's causing the file to be removed. We just need it to be copied again.

**Comment by pires** [comment]
@windwizard care to check on this? It seems your #93 broke said behavior.

**Comment by windwizard** [comment]
@pires  Sorry, It's my fault. by default, my #93 will remove the vagrantfile-user-data for every vagrant halt / reload. And it suppose to run 'vagrant up --provision' or 'vagrant reload --provision' to re-generate the file.

I've made #99  to fix this issue. Sorry for the trouble

**Comment by pires** [comment]
Care to try it now @heytrav?

**Comment by heytrav** [comment]
:+1:  Looks good. It no longer hangs bringing up master and the cloud-config for the nodes looks like the node.yaml file.

**Comment by pires** [comment]
@heytrav thank you for taking the time to debug this.
